# GUIDIANCE SETTINGS:
SKIP_BOOSTERBACK = False
SKIP_AERODYNAMIC_GUIDANCE = False
SKIP_ENTRYBURN = False

# GLOBAL SETTINGS:
MAX_TILT = 30
THROTTLE_LIMIT = [0.1, 1]

# GFOLD PARAMS:
GFOLD_START_VELOCITY = 340

# OTHER SETTINGS:
LAND_CONFIRM = True
LANDING_GEAR = True