# GUIDIANCE SETTINGS:
SKIP_BOOSTERBACK = False
SKIP_REENTRY_BURN = False
SKIP_AERODYNAMIC_GUIDANCE = False

# GLOBAL SETTINGS:
MAX_TILT = 10
THROTTLE_LIMIT = [0.1, 1]

# REENTRY BURN SETTINGS:
START_ALTITUDE = 80000
TARGET_VELOCITY = 100
TARGET_ALTITUDE = 70000

# GFOLD PARAMS:
GFOLD_START_ALTITUDE = 2000
GFOLD_START_VELOCITY = 80

# PID GUIDANCE SETTINGS:
LAND_CONFIRM = True