# GUIDIANCE SETTINGS:
SKIP_BOOSTERBACK = False
SKIP_AERODYNAMIC_GUIDANCE = False

# GLOBAL SETTINGS:
MAX_TILT = 10
THROTTLE_LIMIT = [0.1, 1]

# GFOLD PARAMS:
GFOLD_START_VELOCITY = 100

# PID GUIDANCE SETTINGS:
HOVER_ALTITUDE = 70