
/*
Auto-generated by CVXPYgen on January 12, 2026 at 10:53:18.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_initial_position(0, 450.00000000000000000000);
  cpg_update_initial_velocity(0, -40.00000000000000000000);
  cpg_update_log_mass(7.60090245954208221235);
  cpg_update_max_vel(1000.00000000000000000000);
  cpg_update_sin_glide_slope(0.00000000000000000000);
  cpg_update_z0(0, 7.60090245954208221235);
  cpg_update_min_exp_z0(0, 0.41666666666666662966);
  cpg_update_max_exp_z0(0, 0.10416666666666665741);
  cpg_update_dt(0.44630000000000003002);
  cpg_update_dt_squared(0.19918369000000002433);
  cpg_update_gravity_dt_squared(0, 0.00000000000000000000);
  cpg_update_gravity_dt(0, 0.00000000000000000000);
  cpg_update_fuel_consumption_dt(0.00022315000000000003);
  cpg_update_target_velocity(0, 0.00000000000000000000);
  cpg_update_log_dry_mass(5.70378247465620091816);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<100; i++) {
    printf("z[%d] = %f\n", i, CPG_Result.prim->z[i]);
  }
  for(i=0; i<600; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<300; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<100; i++) {
    printf("s[%d] = %f\n", i, CPG_Result.prim->s[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  printf("d3 = %f\n", CPG_Result.dual->d3);
  printf("d4 = %f\n", CPG_Result.dual->d4);
  printf("d5 = %f\n", CPG_Result.dual->d5);
  printf("d6 = %f\n", CPG_Result.dual->d6);
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  printf("d9 = %f\n", CPG_Result.dual->d9);
  for(i=0; i<3; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<3; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  printf("d12 = %f\n", CPG_Result.dual->d12);
  printf("d13 = %f\n", CPG_Result.dual->d13);
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  printf("d17 = %f\n", CPG_Result.dual->d17);
  printf("d18 = %f\n", CPG_Result.dual->d18);
  printf("d19 = %f\n", CPG_Result.dual->d19);
  printf("d20 = %f\n", CPG_Result.dual->d20);
  for(i=0; i<3; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<3; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  printf("d23 = %f\n", CPG_Result.dual->d23);
  printf("d24 = %f\n", CPG_Result.dual->d24);
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  printf("d27 = %f\n", CPG_Result.dual->d27);
  printf("d28 = %f\n", CPG_Result.dual->d28);
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  for(i=0; i<3; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<3; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  for(i=0; i<3; i++) {
    printf("d43[%d] = %f\n", i, CPG_Result.dual->d43[i]);
  }
  for(i=0; i<3; i++) {
    printf("d44[%d] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  for(i=0; i<3; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<3; i++) {
    printf("d55[%d] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  for(i=0; i<3; i++) {
    printf("d65[%d] = %f\n", i, CPG_Result.dual->d65[i]);
  }
  for(i=0; i<3; i++) {
    printf("d66[%d] = %f\n", i, CPG_Result.dual->d66[i]);
  }
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  for(i=0; i<3; i++) {
    printf("d76[%d] = %f\n", i, CPG_Result.dual->d76[i]);
  }
  for(i=0; i<3; i++) {
    printf("d77[%d] = %f\n", i, CPG_Result.dual->d77[i]);
  }
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  for(i=0; i<3; i++) {
    printf("d87[%d] = %f\n", i, CPG_Result.dual->d87[i]);
  }
  for(i=0; i<3; i++) {
    printf("d88[%d] = %f\n", i, CPG_Result.dual->d88[i]);
  }
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  for(i=0; i<3; i++) {
    printf("d98[%d] = %f\n", i, CPG_Result.dual->d98[i]);
  }
  for(i=0; i<3; i++) {
    printf("d99[%d] = %f\n", i, CPG_Result.dual->d99[i]);
  }
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  for(i=0; i<3; i++) {
    printf("d109[%d] = %f\n", i, CPG_Result.dual->d109[i]);
  }
  for(i=0; i<3; i++) {
    printf("d110[%d] = %f\n", i, CPG_Result.dual->d110[i]);
  }
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  for(i=0; i<3; i++) {
    printf("d120[%d] = %f\n", i, CPG_Result.dual->d120[i]);
  }
  for(i=0; i<3; i++) {
    printf("d121[%d] = %f\n", i, CPG_Result.dual->d121[i]);
  }
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  for(i=0; i<3; i++) {
    printf("d131[%d] = %f\n", i, CPG_Result.dual->d131[i]);
  }
  for(i=0; i<3; i++) {
    printf("d132[%d] = %f\n", i, CPG_Result.dual->d132[i]);
  }
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  for(i=0; i<3; i++) {
    printf("d142[%d] = %f\n", i, CPG_Result.dual->d142[i]);
  }
  for(i=0; i<3; i++) {
    printf("d143[%d] = %f\n", i, CPG_Result.dual->d143[i]);
  }
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);
  printf("d151 = %f\n", CPG_Result.dual->d151);
  printf("d152 = %f\n", CPG_Result.dual->d152);
  for(i=0; i<3; i++) {
    printf("d153[%d] = %f\n", i, CPG_Result.dual->d153[i]);
  }
  for(i=0; i<3; i++) {
    printf("d154[%d] = %f\n", i, CPG_Result.dual->d154[i]);
  }
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  printf("d158 = %f\n", CPG_Result.dual->d158);
  printf("d159 = %f\n", CPG_Result.dual->d159);
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  printf("d162 = %f\n", CPG_Result.dual->d162);
  printf("d163 = %f\n", CPG_Result.dual->d163);
  for(i=0; i<3; i++) {
    printf("d164[%d] = %f\n", i, CPG_Result.dual->d164[i]);
  }
  for(i=0; i<3; i++) {
    printf("d165[%d] = %f\n", i, CPG_Result.dual->d165[i]);
  }
  printf("d166 = %f\n", CPG_Result.dual->d166);
  printf("d167 = %f\n", CPG_Result.dual->d167);
  printf("d168 = %f\n", CPG_Result.dual->d168);
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  printf("d171 = %f\n", CPG_Result.dual->d171);
  printf("d172 = %f\n", CPG_Result.dual->d172);
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  for(i=0; i<3; i++) {
    printf("d175[%d] = %f\n", i, CPG_Result.dual->d175[i]);
  }
  for(i=0; i<3; i++) {
    printf("d176[%d] = %f\n", i, CPG_Result.dual->d176[i]);
  }
  printf("d177 = %f\n", CPG_Result.dual->d177);
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  printf("d180 = %f\n", CPG_Result.dual->d180);
  printf("d181 = %f\n", CPG_Result.dual->d181);
  printf("d182 = %f\n", CPG_Result.dual->d182);
  printf("d183 = %f\n", CPG_Result.dual->d183);
  printf("d184 = %f\n", CPG_Result.dual->d184);
  printf("d185 = %f\n", CPG_Result.dual->d185);
  for(i=0; i<3; i++) {
    printf("d186[%d] = %f\n", i, CPG_Result.dual->d186[i]);
  }
  for(i=0; i<3; i++) {
    printf("d187[%d] = %f\n", i, CPG_Result.dual->d187[i]);
  }
  printf("d188 = %f\n", CPG_Result.dual->d188);
  printf("d189 = %f\n", CPG_Result.dual->d189);
  printf("d190 = %f\n", CPG_Result.dual->d190);
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  printf("d194 = %f\n", CPG_Result.dual->d194);
  printf("d195 = %f\n", CPG_Result.dual->d195);
  printf("d196 = %f\n", CPG_Result.dual->d196);
  for(i=0; i<3; i++) {
    printf("d197[%d] = %f\n", i, CPG_Result.dual->d197[i]);
  }
  for(i=0; i<3; i++) {
    printf("d198[%d] = %f\n", i, CPG_Result.dual->d198[i]);
  }
  printf("d199 = %f\n", CPG_Result.dual->d199);
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  printf("d203 = %f\n", CPG_Result.dual->d203);
  printf("d204 = %f\n", CPG_Result.dual->d204);
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  printf("d207 = %f\n", CPG_Result.dual->d207);
  for(i=0; i<3; i++) {
    printf("d208[%d] = %f\n", i, CPG_Result.dual->d208[i]);
  }
  for(i=0; i<3; i++) {
    printf("d209[%d] = %f\n", i, CPG_Result.dual->d209[i]);
  }
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  printf("d212 = %f\n", CPG_Result.dual->d212);
  printf("d213 = %f\n", CPG_Result.dual->d213);
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);
  printf("d216 = %f\n", CPG_Result.dual->d216);
  printf("d217 = %f\n", CPG_Result.dual->d217);
  printf("d218 = %f\n", CPG_Result.dual->d218);
  for(i=0; i<3; i++) {
    printf("d219[%d] = %f\n", i, CPG_Result.dual->d219[i]);
  }
  for(i=0; i<3; i++) {
    printf("d220[%d] = %f\n", i, CPG_Result.dual->d220[i]);
  }
  printf("d221 = %f\n", CPG_Result.dual->d221);
  printf("d222 = %f\n", CPG_Result.dual->d222);
  printf("d223 = %f\n", CPG_Result.dual->d223);
  printf("d224 = %f\n", CPG_Result.dual->d224);
  printf("d225 = %f\n", CPG_Result.dual->d225);
  printf("d226 = %f\n", CPG_Result.dual->d226);
  printf("d227 = %f\n", CPG_Result.dual->d227);
  printf("d228 = %f\n", CPG_Result.dual->d228);
  printf("d229 = %f\n", CPG_Result.dual->d229);
  for(i=0; i<3; i++) {
    printf("d230[%d] = %f\n", i, CPG_Result.dual->d230[i]);
  }
  for(i=0; i<3; i++) {
    printf("d231[%d] = %f\n", i, CPG_Result.dual->d231[i]);
  }
  printf("d232 = %f\n", CPG_Result.dual->d232);
  printf("d233 = %f\n", CPG_Result.dual->d233);
  printf("d234 = %f\n", CPG_Result.dual->d234);
  printf("d235 = %f\n", CPG_Result.dual->d235);
  printf("d236 = %f\n", CPG_Result.dual->d236);
  printf("d237 = %f\n", CPG_Result.dual->d237);
  printf("d238 = %f\n", CPG_Result.dual->d238);
  printf("d239 = %f\n", CPG_Result.dual->d239);
  printf("d240 = %f\n", CPG_Result.dual->d240);
  for(i=0; i<3; i++) {
    printf("d241[%d] = %f\n", i, CPG_Result.dual->d241[i]);
  }
  for(i=0; i<3; i++) {
    printf("d242[%d] = %f\n", i, CPG_Result.dual->d242[i]);
  }
  printf("d243 = %f\n", CPG_Result.dual->d243);
  printf("d244 = %f\n", CPG_Result.dual->d244);
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  printf("d248 = %f\n", CPG_Result.dual->d248);
  printf("d249 = %f\n", CPG_Result.dual->d249);
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  for(i=0; i<3; i++) {
    printf("d252[%d] = %f\n", i, CPG_Result.dual->d252[i]);
  }
  for(i=0; i<3; i++) {
    printf("d253[%d] = %f\n", i, CPG_Result.dual->d253[i]);
  }
  printf("d254 = %f\n", CPG_Result.dual->d254);
  printf("d255 = %f\n", CPG_Result.dual->d255);
  printf("d256 = %f\n", CPG_Result.dual->d256);
  printf("d257 = %f\n", CPG_Result.dual->d257);
  printf("d258 = %f\n", CPG_Result.dual->d258);
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  printf("d261 = %f\n", CPG_Result.dual->d261);
  printf("d262 = %f\n", CPG_Result.dual->d262);
  for(i=0; i<3; i++) {
    printf("d263[%d] = %f\n", i, CPG_Result.dual->d263[i]);
  }
  for(i=0; i<3; i++) {
    printf("d264[%d] = %f\n", i, CPG_Result.dual->d264[i]);
  }
  printf("d265 = %f\n", CPG_Result.dual->d265);
  printf("d266 = %f\n", CPG_Result.dual->d266);
  printf("d267 = %f\n", CPG_Result.dual->d267);
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  printf("d270 = %f\n", CPG_Result.dual->d270);
  printf("d271 = %f\n", CPG_Result.dual->d271);
  printf("d272 = %f\n", CPG_Result.dual->d272);
  printf("d273 = %f\n", CPG_Result.dual->d273);
  for(i=0; i<3; i++) {
    printf("d274[%d] = %f\n", i, CPG_Result.dual->d274[i]);
  }
  for(i=0; i<3; i++) {
    printf("d275[%d] = %f\n", i, CPG_Result.dual->d275[i]);
  }
  printf("d276 = %f\n", CPG_Result.dual->d276);
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  printf("d279 = %f\n", CPG_Result.dual->d279);
  printf("d280 = %f\n", CPG_Result.dual->d280);
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  printf("d284 = %f\n", CPG_Result.dual->d284);
  for(i=0; i<3; i++) {
    printf("d285[%d] = %f\n", i, CPG_Result.dual->d285[i]);
  }
  for(i=0; i<3; i++) {
    printf("d286[%d] = %f\n", i, CPG_Result.dual->d286[i]);
  }
  printf("d287 = %f\n", CPG_Result.dual->d287);
  printf("d288 = %f\n", CPG_Result.dual->d288);
  printf("d289 = %f\n", CPG_Result.dual->d289);
  printf("d290 = %f\n", CPG_Result.dual->d290);
  printf("d291 = %f\n", CPG_Result.dual->d291);
  printf("d292 = %f\n", CPG_Result.dual->d292);
  printf("d293 = %f\n", CPG_Result.dual->d293);
  printf("d294 = %f\n", CPG_Result.dual->d294);
  printf("d295 = %f\n", CPG_Result.dual->d295);
  for(i=0; i<3; i++) {
    printf("d296[%d] = %f\n", i, CPG_Result.dual->d296[i]);
  }
  for(i=0; i<3; i++) {
    printf("d297[%d] = %f\n", i, CPG_Result.dual->d297[i]);
  }
  printf("d298 = %f\n", CPG_Result.dual->d298);
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);
  printf("d302 = %f\n", CPG_Result.dual->d302);
  printf("d303 = %f\n", CPG_Result.dual->d303);
  printf("d304 = %f\n", CPG_Result.dual->d304);
  printf("d305 = %f\n", CPG_Result.dual->d305);
  printf("d306 = %f\n", CPG_Result.dual->d306);
  for(i=0; i<3; i++) {
    printf("d307[%d] = %f\n", i, CPG_Result.dual->d307[i]);
  }
  for(i=0; i<3; i++) {
    printf("d308[%d] = %f\n", i, CPG_Result.dual->d308[i]);
  }
  printf("d309 = %f\n", CPG_Result.dual->d309);
  printf("d310 = %f\n", CPG_Result.dual->d310);
  printf("d311 = %f\n", CPG_Result.dual->d311);
  printf("d312 = %f\n", CPG_Result.dual->d312);
  printf("d313 = %f\n", CPG_Result.dual->d313);
  printf("d314 = %f\n", CPG_Result.dual->d314);
  printf("d315 = %f\n", CPG_Result.dual->d315);
  printf("d316 = %f\n", CPG_Result.dual->d316);
  printf("d317 = %f\n", CPG_Result.dual->d317);
  for(i=0; i<3; i++) {
    printf("d318[%d] = %f\n", i, CPG_Result.dual->d318[i]);
  }
  for(i=0; i<3; i++) {
    printf("d319[%d] = %f\n", i, CPG_Result.dual->d319[i]);
  }
  printf("d320 = %f\n", CPG_Result.dual->d320);
  printf("d321 = %f\n", CPG_Result.dual->d321);
  printf("d322 = %f\n", CPG_Result.dual->d322);
  printf("d323 = %f\n", CPG_Result.dual->d323);
  printf("d324 = %f\n", CPG_Result.dual->d324);
  printf("d325 = %f\n", CPG_Result.dual->d325);
  printf("d326 = %f\n", CPG_Result.dual->d326);
  printf("d327 = %f\n", CPG_Result.dual->d327);
  printf("d328 = %f\n", CPG_Result.dual->d328);
  for(i=0; i<3; i++) {
    printf("d329[%d] = %f\n", i, CPG_Result.dual->d329[i]);
  }
  for(i=0; i<3; i++) {
    printf("d330[%d] = %f\n", i, CPG_Result.dual->d330[i]);
  }
  printf("d331 = %f\n", CPG_Result.dual->d331);
  printf("d332 = %f\n", CPG_Result.dual->d332);
  printf("d333 = %f\n", CPG_Result.dual->d333);
  printf("d334 = %f\n", CPG_Result.dual->d334);
  printf("d335 = %f\n", CPG_Result.dual->d335);
  printf("d336 = %f\n", CPG_Result.dual->d336);
  printf("d337 = %f\n", CPG_Result.dual->d337);
  printf("d338 = %f\n", CPG_Result.dual->d338);
  printf("d339 = %f\n", CPG_Result.dual->d339);
  for(i=0; i<3; i++) {
    printf("d340[%d] = %f\n", i, CPG_Result.dual->d340[i]);
  }
  for(i=0; i<3; i++) {
    printf("d341[%d] = %f\n", i, CPG_Result.dual->d341[i]);
  }
  printf("d342 = %f\n", CPG_Result.dual->d342);
  printf("d343 = %f\n", CPG_Result.dual->d343);
  printf("d344 = %f\n", CPG_Result.dual->d344);
  printf("d345 = %f\n", CPG_Result.dual->d345);
  printf("d346 = %f\n", CPG_Result.dual->d346);
  printf("d347 = %f\n", CPG_Result.dual->d347);
  printf("d348 = %f\n", CPG_Result.dual->d348);
  printf("d349 = %f\n", CPG_Result.dual->d349);
  printf("d350 = %f\n", CPG_Result.dual->d350);
  for(i=0; i<3; i++) {
    printf("d351[%d] = %f\n", i, CPG_Result.dual->d351[i]);
  }
  for(i=0; i<3; i++) {
    printf("d352[%d] = %f\n", i, CPG_Result.dual->d352[i]);
  }
  printf("d353 = %f\n", CPG_Result.dual->d353);
  printf("d354 = %f\n", CPG_Result.dual->d354);
  printf("d355 = %f\n", CPG_Result.dual->d355);
  printf("d356 = %f\n", CPG_Result.dual->d356);
  printf("d357 = %f\n", CPG_Result.dual->d357);
  printf("d358 = %f\n", CPG_Result.dual->d358);
  printf("d359 = %f\n", CPG_Result.dual->d359);
  printf("d360 = %f\n", CPG_Result.dual->d360);
  printf("d361 = %f\n", CPG_Result.dual->d361);
  for(i=0; i<3; i++) {
    printf("d362[%d] = %f\n", i, CPG_Result.dual->d362[i]);
  }
  for(i=0; i<3; i++) {
    printf("d363[%d] = %f\n", i, CPG_Result.dual->d363[i]);
  }
  printf("d364 = %f\n", CPG_Result.dual->d364);
  printf("d365 = %f\n", CPG_Result.dual->d365);
  printf("d366 = %f\n", CPG_Result.dual->d366);
  printf("d367 = %f\n", CPG_Result.dual->d367);
  printf("d368 = %f\n", CPG_Result.dual->d368);
  printf("d369 = %f\n", CPG_Result.dual->d369);
  printf("d370 = %f\n", CPG_Result.dual->d370);
  printf("d371 = %f\n", CPG_Result.dual->d371);
  printf("d372 = %f\n", CPG_Result.dual->d372);
  for(i=0; i<3; i++) {
    printf("d373[%d] = %f\n", i, CPG_Result.dual->d373[i]);
  }
  for(i=0; i<3; i++) {
    printf("d374[%d] = %f\n", i, CPG_Result.dual->d374[i]);
  }
  printf("d375 = %f\n", CPG_Result.dual->d375);
  printf("d376 = %f\n", CPG_Result.dual->d376);
  printf("d377 = %f\n", CPG_Result.dual->d377);
  printf("d378 = %f\n", CPG_Result.dual->d378);
  printf("d379 = %f\n", CPG_Result.dual->d379);
  printf("d380 = %f\n", CPG_Result.dual->d380);
  printf("d381 = %f\n", CPG_Result.dual->d381);
  printf("d382 = %f\n", CPG_Result.dual->d382);
  printf("d383 = %f\n", CPG_Result.dual->d383);
  for(i=0; i<3; i++) {
    printf("d384[%d] = %f\n", i, CPG_Result.dual->d384[i]);
  }
  for(i=0; i<3; i++) {
    printf("d385[%d] = %f\n", i, CPG_Result.dual->d385[i]);
  }
  printf("d386 = %f\n", CPG_Result.dual->d386);
  printf("d387 = %f\n", CPG_Result.dual->d387);
  printf("d388 = %f\n", CPG_Result.dual->d388);
  printf("d389 = %f\n", CPG_Result.dual->d389);
  printf("d390 = %f\n", CPG_Result.dual->d390);
  printf("d391 = %f\n", CPG_Result.dual->d391);
  printf("d392 = %f\n", CPG_Result.dual->d392);
  printf("d393 = %f\n", CPG_Result.dual->d393);
  printf("d394 = %f\n", CPG_Result.dual->d394);
  for(i=0; i<3; i++) {
    printf("d395[%d] = %f\n", i, CPG_Result.dual->d395[i]);
  }
  for(i=0; i<3; i++) {
    printf("d396[%d] = %f\n", i, CPG_Result.dual->d396[i]);
  }
  printf("d397 = %f\n", CPG_Result.dual->d397);
  printf("d398 = %f\n", CPG_Result.dual->d398);
  printf("d399 = %f\n", CPG_Result.dual->d399);
  printf("d400 = %f\n", CPG_Result.dual->d400);
  printf("d401 = %f\n", CPG_Result.dual->d401);
  printf("d402 = %f\n", CPG_Result.dual->d402);
  printf("d403 = %f\n", CPG_Result.dual->d403);
  printf("d404 = %f\n", CPG_Result.dual->d404);
  printf("d405 = %f\n", CPG_Result.dual->d405);
  for(i=0; i<3; i++) {
    printf("d406[%d] = %f\n", i, CPG_Result.dual->d406[i]);
  }
  for(i=0; i<3; i++) {
    printf("d407[%d] = %f\n", i, CPG_Result.dual->d407[i]);
  }
  printf("d408 = %f\n", CPG_Result.dual->d408);
  printf("d409 = %f\n", CPG_Result.dual->d409);
  printf("d410 = %f\n", CPG_Result.dual->d410);
  printf("d411 = %f\n", CPG_Result.dual->d411);
  printf("d412 = %f\n", CPG_Result.dual->d412);
  printf("d413 = %f\n", CPG_Result.dual->d413);
  printf("d414 = %f\n", CPG_Result.dual->d414);
  printf("d415 = %f\n", CPG_Result.dual->d415);
  printf("d416 = %f\n", CPG_Result.dual->d416);
  for(i=0; i<3; i++) {
    printf("d417[%d] = %f\n", i, CPG_Result.dual->d417[i]);
  }
  for(i=0; i<3; i++) {
    printf("d418[%d] = %f\n", i, CPG_Result.dual->d418[i]);
  }
  printf("d419 = %f\n", CPG_Result.dual->d419);
  printf("d420 = %f\n", CPG_Result.dual->d420);
  printf("d421 = %f\n", CPG_Result.dual->d421);
  printf("d422 = %f\n", CPG_Result.dual->d422);
  printf("d423 = %f\n", CPG_Result.dual->d423);
  printf("d424 = %f\n", CPG_Result.dual->d424);
  printf("d425 = %f\n", CPG_Result.dual->d425);
  printf("d426 = %f\n", CPG_Result.dual->d426);
  printf("d427 = %f\n", CPG_Result.dual->d427);
  for(i=0; i<3; i++) {
    printf("d428[%d] = %f\n", i, CPG_Result.dual->d428[i]);
  }
  for(i=0; i<3; i++) {
    printf("d429[%d] = %f\n", i, CPG_Result.dual->d429[i]);
  }
  printf("d430 = %f\n", CPG_Result.dual->d430);
  printf("d431 = %f\n", CPG_Result.dual->d431);
  printf("d432 = %f\n", CPG_Result.dual->d432);
  printf("d433 = %f\n", CPG_Result.dual->d433);
  printf("d434 = %f\n", CPG_Result.dual->d434);
  printf("d435 = %f\n", CPG_Result.dual->d435);
  printf("d436 = %f\n", CPG_Result.dual->d436);
  printf("d437 = %f\n", CPG_Result.dual->d437);
  printf("d438 = %f\n", CPG_Result.dual->d438);
  for(i=0; i<3; i++) {
    printf("d439[%d] = %f\n", i, CPG_Result.dual->d439[i]);
  }
  for(i=0; i<3; i++) {
    printf("d440[%d] = %f\n", i, CPG_Result.dual->d440[i]);
  }
  printf("d441 = %f\n", CPG_Result.dual->d441);
  printf("d442 = %f\n", CPG_Result.dual->d442);
  printf("d443 = %f\n", CPG_Result.dual->d443);
  printf("d444 = %f\n", CPG_Result.dual->d444);
  printf("d445 = %f\n", CPG_Result.dual->d445);
  printf("d446 = %f\n", CPG_Result.dual->d446);
  printf("d447 = %f\n", CPG_Result.dual->d447);
  printf("d448 = %f\n", CPG_Result.dual->d448);
  printf("d449 = %f\n", CPG_Result.dual->d449);
  for(i=0; i<3; i++) {
    printf("d450[%d] = %f\n", i, CPG_Result.dual->d450[i]);
  }
  for(i=0; i<3; i++) {
    printf("d451[%d] = %f\n", i, CPG_Result.dual->d451[i]);
  }
  printf("d452 = %f\n", CPG_Result.dual->d452);
  printf("d453 = %f\n", CPG_Result.dual->d453);
  printf("d454 = %f\n", CPG_Result.dual->d454);
  printf("d455 = %f\n", CPG_Result.dual->d455);
  printf("d456 = %f\n", CPG_Result.dual->d456);
  printf("d457 = %f\n", CPG_Result.dual->d457);
  printf("d458 = %f\n", CPG_Result.dual->d458);
  printf("d459 = %f\n", CPG_Result.dual->d459);
  printf("d460 = %f\n", CPG_Result.dual->d460);
  for(i=0; i<3; i++) {
    printf("d461[%d] = %f\n", i, CPG_Result.dual->d461[i]);
  }
  for(i=0; i<3; i++) {
    printf("d462[%d] = %f\n", i, CPG_Result.dual->d462[i]);
  }
  printf("d463 = %f\n", CPG_Result.dual->d463);
  printf("d464 = %f\n", CPG_Result.dual->d464);
  printf("d465 = %f\n", CPG_Result.dual->d465);
  printf("d466 = %f\n", CPG_Result.dual->d466);
  printf("d467 = %f\n", CPG_Result.dual->d467);
  printf("d468 = %f\n", CPG_Result.dual->d468);
  printf("d469 = %f\n", CPG_Result.dual->d469);
  printf("d470 = %f\n", CPG_Result.dual->d470);
  printf("d471 = %f\n", CPG_Result.dual->d471);
  for(i=0; i<3; i++) {
    printf("d472[%d] = %f\n", i, CPG_Result.dual->d472[i]);
  }
  for(i=0; i<3; i++) {
    printf("d473[%d] = %f\n", i, CPG_Result.dual->d473[i]);
  }
  printf("d474 = %f\n", CPG_Result.dual->d474);
  printf("d475 = %f\n", CPG_Result.dual->d475);
  printf("d476 = %f\n", CPG_Result.dual->d476);
  printf("d477 = %f\n", CPG_Result.dual->d477);
  printf("d478 = %f\n", CPG_Result.dual->d478);
  printf("d479 = %f\n", CPG_Result.dual->d479);
  printf("d480 = %f\n", CPG_Result.dual->d480);
  printf("d481 = %f\n", CPG_Result.dual->d481);
  printf("d482 = %f\n", CPG_Result.dual->d482);
  for(i=0; i<3; i++) {
    printf("d483[%d] = %f\n", i, CPG_Result.dual->d483[i]);
  }
  for(i=0; i<3; i++) {
    printf("d484[%d] = %f\n", i, CPG_Result.dual->d484[i]);
  }
  printf("d485 = %f\n", CPG_Result.dual->d485);
  printf("d486 = %f\n", CPG_Result.dual->d486);
  printf("d487 = %f\n", CPG_Result.dual->d487);
  printf("d488 = %f\n", CPG_Result.dual->d488);
  printf("d489 = %f\n", CPG_Result.dual->d489);
  printf("d490 = %f\n", CPG_Result.dual->d490);
  printf("d491 = %f\n", CPG_Result.dual->d491);
  printf("d492 = %f\n", CPG_Result.dual->d492);
  printf("d493 = %f\n", CPG_Result.dual->d493);
  for(i=0; i<3; i++) {
    printf("d494[%d] = %f\n", i, CPG_Result.dual->d494[i]);
  }
  for(i=0; i<3; i++) {
    printf("d495[%d] = %f\n", i, CPG_Result.dual->d495[i]);
  }
  printf("d496 = %f\n", CPG_Result.dual->d496);
  printf("d497 = %f\n", CPG_Result.dual->d497);
  printf("d498 = %f\n", CPG_Result.dual->d498);
  printf("d499 = %f\n", CPG_Result.dual->d499);
  printf("d500 = %f\n", CPG_Result.dual->d500);
  printf("d501 = %f\n", CPG_Result.dual->d501);
  printf("d502 = %f\n", CPG_Result.dual->d502);
  printf("d503 = %f\n", CPG_Result.dual->d503);
  printf("d504 = %f\n", CPG_Result.dual->d504);
  for(i=0; i<3; i++) {
    printf("d505[%d] = %f\n", i, CPG_Result.dual->d505[i]);
  }
  for(i=0; i<3; i++) {
    printf("d506[%d] = %f\n", i, CPG_Result.dual->d506[i]);
  }
  printf("d507 = %f\n", CPG_Result.dual->d507);
  printf("d508 = %f\n", CPG_Result.dual->d508);
  printf("d509 = %f\n", CPG_Result.dual->d509);
  printf("d510 = %f\n", CPG_Result.dual->d510);
  printf("d511 = %f\n", CPG_Result.dual->d511);
  printf("d512 = %f\n", CPG_Result.dual->d512);
  printf("d513 = %f\n", CPG_Result.dual->d513);
  printf("d514 = %f\n", CPG_Result.dual->d514);
  printf("d515 = %f\n", CPG_Result.dual->d515);
  for(i=0; i<3; i++) {
    printf("d516[%d] = %f\n", i, CPG_Result.dual->d516[i]);
  }
  for(i=0; i<3; i++) {
    printf("d517[%d] = %f\n", i, CPG_Result.dual->d517[i]);
  }
  printf("d518 = %f\n", CPG_Result.dual->d518);
  printf("d519 = %f\n", CPG_Result.dual->d519);
  printf("d520 = %f\n", CPG_Result.dual->d520);
  printf("d521 = %f\n", CPG_Result.dual->d521);
  printf("d522 = %f\n", CPG_Result.dual->d522);
  printf("d523 = %f\n", CPG_Result.dual->d523);
  printf("d524 = %f\n", CPG_Result.dual->d524);
  printf("d525 = %f\n", CPG_Result.dual->d525);
  printf("d526 = %f\n", CPG_Result.dual->d526);
  for(i=0; i<3; i++) {
    printf("d527[%d] = %f\n", i, CPG_Result.dual->d527[i]);
  }
  for(i=0; i<3; i++) {
    printf("d528[%d] = %f\n", i, CPG_Result.dual->d528[i]);
  }
  printf("d529 = %f\n", CPG_Result.dual->d529);
  printf("d530 = %f\n", CPG_Result.dual->d530);
  printf("d531 = %f\n", CPG_Result.dual->d531);
  printf("d532 = %f\n", CPG_Result.dual->d532);
  printf("d533 = %f\n", CPG_Result.dual->d533);
  printf("d534 = %f\n", CPG_Result.dual->d534);
  printf("d535 = %f\n", CPG_Result.dual->d535);
  printf("d536 = %f\n", CPG_Result.dual->d536);
  printf("d537 = %f\n", CPG_Result.dual->d537);
  for(i=0; i<3; i++) {
    printf("d538[%d] = %f\n", i, CPG_Result.dual->d538[i]);
  }
  for(i=0; i<3; i++) {
    printf("d539[%d] = %f\n", i, CPG_Result.dual->d539[i]);
  }
  printf("d540 = %f\n", CPG_Result.dual->d540);
  printf("d541 = %f\n", CPG_Result.dual->d541);
  printf("d542 = %f\n", CPG_Result.dual->d542);
  printf("d543 = %f\n", CPG_Result.dual->d543);
  printf("d544 = %f\n", CPG_Result.dual->d544);
  printf("d545 = %f\n", CPG_Result.dual->d545);
  printf("d546 = %f\n", CPG_Result.dual->d546);
  printf("d547 = %f\n", CPG_Result.dual->d547);
  printf("d548 = %f\n", CPG_Result.dual->d548);
  for(i=0; i<3; i++) {
    printf("d549[%d] = %f\n", i, CPG_Result.dual->d549[i]);
  }
  for(i=0; i<3; i++) {
    printf("d550[%d] = %f\n", i, CPG_Result.dual->d550[i]);
  }
  printf("d551 = %f\n", CPG_Result.dual->d551);
  printf("d552 = %f\n", CPG_Result.dual->d552);
  printf("d553 = %f\n", CPG_Result.dual->d553);
  printf("d554 = %f\n", CPG_Result.dual->d554);
  printf("d555 = %f\n", CPG_Result.dual->d555);
  printf("d556 = %f\n", CPG_Result.dual->d556);
  printf("d557 = %f\n", CPG_Result.dual->d557);
  printf("d558 = %f\n", CPG_Result.dual->d558);
  printf("d559 = %f\n", CPG_Result.dual->d559);
  for(i=0; i<3; i++) {
    printf("d560[%d] = %f\n", i, CPG_Result.dual->d560[i]);
  }
  for(i=0; i<3; i++) {
    printf("d561[%d] = %f\n", i, CPG_Result.dual->d561[i]);
  }
  printf("d562 = %f\n", CPG_Result.dual->d562);
  printf("d563 = %f\n", CPG_Result.dual->d563);
  printf("d564 = %f\n", CPG_Result.dual->d564);
  printf("d565 = %f\n", CPG_Result.dual->d565);
  printf("d566 = %f\n", CPG_Result.dual->d566);
  printf("d567 = %f\n", CPG_Result.dual->d567);
  printf("d568 = %f\n", CPG_Result.dual->d568);
  printf("d569 = %f\n", CPG_Result.dual->d569);
  printf("d570 = %f\n", CPG_Result.dual->d570);
  for(i=0; i<3; i++) {
    printf("d571[%d] = %f\n", i, CPG_Result.dual->d571[i]);
  }
  for(i=0; i<3; i++) {
    printf("d572[%d] = %f\n", i, CPG_Result.dual->d572[i]);
  }
  printf("d573 = %f\n", CPG_Result.dual->d573);
  printf("d574 = %f\n", CPG_Result.dual->d574);
  printf("d575 = %f\n", CPG_Result.dual->d575);
  printf("d576 = %f\n", CPG_Result.dual->d576);
  printf("d577 = %f\n", CPG_Result.dual->d577);
  printf("d578 = %f\n", CPG_Result.dual->d578);
  printf("d579 = %f\n", CPG_Result.dual->d579);
  printf("d580 = %f\n", CPG_Result.dual->d580);
  printf("d581 = %f\n", CPG_Result.dual->d581);
  for(i=0; i<3; i++) {
    printf("d582[%d] = %f\n", i, CPG_Result.dual->d582[i]);
  }
  for(i=0; i<3; i++) {
    printf("d583[%d] = %f\n", i, CPG_Result.dual->d583[i]);
  }
  printf("d584 = %f\n", CPG_Result.dual->d584);
  printf("d585 = %f\n", CPG_Result.dual->d585);
  printf("d586 = %f\n", CPG_Result.dual->d586);
  printf("d587 = %f\n", CPG_Result.dual->d587);
  printf("d588 = %f\n", CPG_Result.dual->d588);
  printf("d589 = %f\n", CPG_Result.dual->d589);
  printf("d590 = %f\n", CPG_Result.dual->d590);
  printf("d591 = %f\n", CPG_Result.dual->d591);
  printf("d592 = %f\n", CPG_Result.dual->d592);
  for(i=0; i<3; i++) {
    printf("d593[%d] = %f\n", i, CPG_Result.dual->d593[i]);
  }
  for(i=0; i<3; i++) {
    printf("d594[%d] = %f\n", i, CPG_Result.dual->d594[i]);
  }
  printf("d595 = %f\n", CPG_Result.dual->d595);
  printf("d596 = %f\n", CPG_Result.dual->d596);
  printf("d597 = %f\n", CPG_Result.dual->d597);
  printf("d598 = %f\n", CPG_Result.dual->d598);
  printf("d599 = %f\n", CPG_Result.dual->d599);
  printf("d600 = %f\n", CPG_Result.dual->d600);
  printf("d601 = %f\n", CPG_Result.dual->d601);
  printf("d602 = %f\n", CPG_Result.dual->d602);
  printf("d603 = %f\n", CPG_Result.dual->d603);
  for(i=0; i<3; i++) {
    printf("d604[%d] = %f\n", i, CPG_Result.dual->d604[i]);
  }
  for(i=0; i<3; i++) {
    printf("d605[%d] = %f\n", i, CPG_Result.dual->d605[i]);
  }
  printf("d606 = %f\n", CPG_Result.dual->d606);
  printf("d607 = %f\n", CPG_Result.dual->d607);
  printf("d608 = %f\n", CPG_Result.dual->d608);
  printf("d609 = %f\n", CPG_Result.dual->d609);
  printf("d610 = %f\n", CPG_Result.dual->d610);
  printf("d611 = %f\n", CPG_Result.dual->d611);
  printf("d612 = %f\n", CPG_Result.dual->d612);
  printf("d613 = %f\n", CPG_Result.dual->d613);
  printf("d614 = %f\n", CPG_Result.dual->d614);
  for(i=0; i<3; i++) {
    printf("d615[%d] = %f\n", i, CPG_Result.dual->d615[i]);
  }
  for(i=0; i<3; i++) {
    printf("d616[%d] = %f\n", i, CPG_Result.dual->d616[i]);
  }
  printf("d617 = %f\n", CPG_Result.dual->d617);
  printf("d618 = %f\n", CPG_Result.dual->d618);
  printf("d619 = %f\n", CPG_Result.dual->d619);
  printf("d620 = %f\n", CPG_Result.dual->d620);
  printf("d621 = %f\n", CPG_Result.dual->d621);
  printf("d622 = %f\n", CPG_Result.dual->d622);
  printf("d623 = %f\n", CPG_Result.dual->d623);
  printf("d624 = %f\n", CPG_Result.dual->d624);
  printf("d625 = %f\n", CPG_Result.dual->d625);
  for(i=0; i<3; i++) {
    printf("d626[%d] = %f\n", i, CPG_Result.dual->d626[i]);
  }
  for(i=0; i<3; i++) {
    printf("d627[%d] = %f\n", i, CPG_Result.dual->d627[i]);
  }
  printf("d628 = %f\n", CPG_Result.dual->d628);
  printf("d629 = %f\n", CPG_Result.dual->d629);
  printf("d630 = %f\n", CPG_Result.dual->d630);
  printf("d631 = %f\n", CPG_Result.dual->d631);
  printf("d632 = %f\n", CPG_Result.dual->d632);
  printf("d633 = %f\n", CPG_Result.dual->d633);
  printf("d634 = %f\n", CPG_Result.dual->d634);
  printf("d635 = %f\n", CPG_Result.dual->d635);
  printf("d636 = %f\n", CPG_Result.dual->d636);
  for(i=0; i<3; i++) {
    printf("d637[%d] = %f\n", i, CPG_Result.dual->d637[i]);
  }
  for(i=0; i<3; i++) {
    printf("d638[%d] = %f\n", i, CPG_Result.dual->d638[i]);
  }
  printf("d639 = %f\n", CPG_Result.dual->d639);
  printf("d640 = %f\n", CPG_Result.dual->d640);
  printf("d641 = %f\n", CPG_Result.dual->d641);
  printf("d642 = %f\n", CPG_Result.dual->d642);
  printf("d643 = %f\n", CPG_Result.dual->d643);
  printf("d644 = %f\n", CPG_Result.dual->d644);
  printf("d645 = %f\n", CPG_Result.dual->d645);
  printf("d646 = %f\n", CPG_Result.dual->d646);
  printf("d647 = %f\n", CPG_Result.dual->d647);
  for(i=0; i<3; i++) {
    printf("d648[%d] = %f\n", i, CPG_Result.dual->d648[i]);
  }
  for(i=0; i<3; i++) {
    printf("d649[%d] = %f\n", i, CPG_Result.dual->d649[i]);
  }
  printf("d650 = %f\n", CPG_Result.dual->d650);
  printf("d651 = %f\n", CPG_Result.dual->d651);
  printf("d652 = %f\n", CPG_Result.dual->d652);
  printf("d653 = %f\n", CPG_Result.dual->d653);
  printf("d654 = %f\n", CPG_Result.dual->d654);
  printf("d655 = %f\n", CPG_Result.dual->d655);
  printf("d656 = %f\n", CPG_Result.dual->d656);
  printf("d657 = %f\n", CPG_Result.dual->d657);
  printf("d658 = %f\n", CPG_Result.dual->d658);
  for(i=0; i<3; i++) {
    printf("d659[%d] = %f\n", i, CPG_Result.dual->d659[i]);
  }
  for(i=0; i<3; i++) {
    printf("d660[%d] = %f\n", i, CPG_Result.dual->d660[i]);
  }
  printf("d661 = %f\n", CPG_Result.dual->d661);
  printf("d662 = %f\n", CPG_Result.dual->d662);
  printf("d663 = %f\n", CPG_Result.dual->d663);
  printf("d664 = %f\n", CPG_Result.dual->d664);
  printf("d665 = %f\n", CPG_Result.dual->d665);
  printf("d666 = %f\n", CPG_Result.dual->d666);
  printf("d667 = %f\n", CPG_Result.dual->d667);
  printf("d668 = %f\n", CPG_Result.dual->d668);
  printf("d669 = %f\n", CPG_Result.dual->d669);
  for(i=0; i<3; i++) {
    printf("d670[%d] = %f\n", i, CPG_Result.dual->d670[i]);
  }
  for(i=0; i<3; i++) {
    printf("d671[%d] = %f\n", i, CPG_Result.dual->d671[i]);
  }
  printf("d672 = %f\n", CPG_Result.dual->d672);
  printf("d673 = %f\n", CPG_Result.dual->d673);
  printf("d674 = %f\n", CPG_Result.dual->d674);
  printf("d675 = %f\n", CPG_Result.dual->d675);
  printf("d676 = %f\n", CPG_Result.dual->d676);
  printf("d677 = %f\n", CPG_Result.dual->d677);
  printf("d678 = %f\n", CPG_Result.dual->d678);
  printf("d679 = %f\n", CPG_Result.dual->d679);
  printf("d680 = %f\n", CPG_Result.dual->d680);
  for(i=0; i<3; i++) {
    printf("d681[%d] = %f\n", i, CPG_Result.dual->d681[i]);
  }
  for(i=0; i<3; i++) {
    printf("d682[%d] = %f\n", i, CPG_Result.dual->d682[i]);
  }
  printf("d683 = %f\n", CPG_Result.dual->d683);
  printf("d684 = %f\n", CPG_Result.dual->d684);
  printf("d685 = %f\n", CPG_Result.dual->d685);
  printf("d686 = %f\n", CPG_Result.dual->d686);
  printf("d687 = %f\n", CPG_Result.dual->d687);
  printf("d688 = %f\n", CPG_Result.dual->d688);
  printf("d689 = %f\n", CPG_Result.dual->d689);
  printf("d690 = %f\n", CPG_Result.dual->d690);
  printf("d691 = %f\n", CPG_Result.dual->d691);
  for(i=0; i<3; i++) {
    printf("d692[%d] = %f\n", i, CPG_Result.dual->d692[i]);
  }
  for(i=0; i<3; i++) {
    printf("d693[%d] = %f\n", i, CPG_Result.dual->d693[i]);
  }
  printf("d694 = %f\n", CPG_Result.dual->d694);
  printf("d695 = %f\n", CPG_Result.dual->d695);
  printf("d696 = %f\n", CPG_Result.dual->d696);
  printf("d697 = %f\n", CPG_Result.dual->d697);
  printf("d698 = %f\n", CPG_Result.dual->d698);
  printf("d699 = %f\n", CPG_Result.dual->d699);
  printf("d700 = %f\n", CPG_Result.dual->d700);
  printf("d701 = %f\n", CPG_Result.dual->d701);
  printf("d702 = %f\n", CPG_Result.dual->d702);
  for(i=0; i<3; i++) {
    printf("d703[%d] = %f\n", i, CPG_Result.dual->d703[i]);
  }
  for(i=0; i<3; i++) {
    printf("d704[%d] = %f\n", i, CPG_Result.dual->d704[i]);
  }
  printf("d705 = %f\n", CPG_Result.dual->d705);
  printf("d706 = %f\n", CPG_Result.dual->d706);
  printf("d707 = %f\n", CPG_Result.dual->d707);
  printf("d708 = %f\n", CPG_Result.dual->d708);
  printf("d709 = %f\n", CPG_Result.dual->d709);
  printf("d710 = %f\n", CPG_Result.dual->d710);
  printf("d711 = %f\n", CPG_Result.dual->d711);
  printf("d712 = %f\n", CPG_Result.dual->d712);
  printf("d713 = %f\n", CPG_Result.dual->d713);
  for(i=0; i<3; i++) {
    printf("d714[%d] = %f\n", i, CPG_Result.dual->d714[i]);
  }
  for(i=0; i<3; i++) {
    printf("d715[%d] = %f\n", i, CPG_Result.dual->d715[i]);
  }
  printf("d716 = %f\n", CPG_Result.dual->d716);
  printf("d717 = %f\n", CPG_Result.dual->d717);
  printf("d718 = %f\n", CPG_Result.dual->d718);
  printf("d719 = %f\n", CPG_Result.dual->d719);
  printf("d720 = %f\n", CPG_Result.dual->d720);
  printf("d721 = %f\n", CPG_Result.dual->d721);
  printf("d722 = %f\n", CPG_Result.dual->d722);
  printf("d723 = %f\n", CPG_Result.dual->d723);
  printf("d724 = %f\n", CPG_Result.dual->d724);
  for(i=0; i<3; i++) {
    printf("d725[%d] = %f\n", i, CPG_Result.dual->d725[i]);
  }
  for(i=0; i<3; i++) {
    printf("d726[%d] = %f\n", i, CPG_Result.dual->d726[i]);
  }
  printf("d727 = %f\n", CPG_Result.dual->d727);
  printf("d728 = %f\n", CPG_Result.dual->d728);
  printf("d729 = %f\n", CPG_Result.dual->d729);
  printf("d730 = %f\n", CPG_Result.dual->d730);
  printf("d731 = %f\n", CPG_Result.dual->d731);
  printf("d732 = %f\n", CPG_Result.dual->d732);
  printf("d733 = %f\n", CPG_Result.dual->d733);
  printf("d734 = %f\n", CPG_Result.dual->d734);
  printf("d735 = %f\n", CPG_Result.dual->d735);
  for(i=0; i<3; i++) {
    printf("d736[%d] = %f\n", i, CPG_Result.dual->d736[i]);
  }
  for(i=0; i<3; i++) {
    printf("d737[%d] = %f\n", i, CPG_Result.dual->d737[i]);
  }
  printf("d738 = %f\n", CPG_Result.dual->d738);
  printf("d739 = %f\n", CPG_Result.dual->d739);
  printf("d740 = %f\n", CPG_Result.dual->d740);
  printf("d741 = %f\n", CPG_Result.dual->d741);
  printf("d742 = %f\n", CPG_Result.dual->d742);
  printf("d743 = %f\n", CPG_Result.dual->d743);
  printf("d744 = %f\n", CPG_Result.dual->d744);
  printf("d745 = %f\n", CPG_Result.dual->d745);
  printf("d746 = %f\n", CPG_Result.dual->d746);
  for(i=0; i<3; i++) {
    printf("d747[%d] = %f\n", i, CPG_Result.dual->d747[i]);
  }
  for(i=0; i<3; i++) {
    printf("d748[%d] = %f\n", i, CPG_Result.dual->d748[i]);
  }
  printf("d749 = %f\n", CPG_Result.dual->d749);
  printf("d750 = %f\n", CPG_Result.dual->d750);
  printf("d751 = %f\n", CPG_Result.dual->d751);
  printf("d752 = %f\n", CPG_Result.dual->d752);
  printf("d753 = %f\n", CPG_Result.dual->d753);
  printf("d754 = %f\n", CPG_Result.dual->d754);
  printf("d755 = %f\n", CPG_Result.dual->d755);
  printf("d756 = %f\n", CPG_Result.dual->d756);
  printf("d757 = %f\n", CPG_Result.dual->d757);
  for(i=0; i<3; i++) {
    printf("d758[%d] = %f\n", i, CPG_Result.dual->d758[i]);
  }
  for(i=0; i<3; i++) {
    printf("d759[%d] = %f\n", i, CPG_Result.dual->d759[i]);
  }
  printf("d760 = %f\n", CPG_Result.dual->d760);
  printf("d761 = %f\n", CPG_Result.dual->d761);
  printf("d762 = %f\n", CPG_Result.dual->d762);
  printf("d763 = %f\n", CPG_Result.dual->d763);
  printf("d764 = %f\n", CPG_Result.dual->d764);
  printf("d765 = %f\n", CPG_Result.dual->d765);
  printf("d766 = %f\n", CPG_Result.dual->d766);
  printf("d767 = %f\n", CPG_Result.dual->d767);
  printf("d768 = %f\n", CPG_Result.dual->d768);
  for(i=0; i<3; i++) {
    printf("d769[%d] = %f\n", i, CPG_Result.dual->d769[i]);
  }
  for(i=0; i<3; i++) {
    printf("d770[%d] = %f\n", i, CPG_Result.dual->d770[i]);
  }
  printf("d771 = %f\n", CPG_Result.dual->d771);
  printf("d772 = %f\n", CPG_Result.dual->d772);
  printf("d773 = %f\n", CPG_Result.dual->d773);
  printf("d774 = %f\n", CPG_Result.dual->d774);
  printf("d775 = %f\n", CPG_Result.dual->d775);
  printf("d776 = %f\n", CPG_Result.dual->d776);
  printf("d777 = %f\n", CPG_Result.dual->d777);
  printf("d778 = %f\n", CPG_Result.dual->d778);
  printf("d779 = %f\n", CPG_Result.dual->d779);
  for(i=0; i<3; i++) {
    printf("d780[%d] = %f\n", i, CPG_Result.dual->d780[i]);
  }
  for(i=0; i<3; i++) {
    printf("d781[%d] = %f\n", i, CPG_Result.dual->d781[i]);
  }
  printf("d782 = %f\n", CPG_Result.dual->d782);
  printf("d783 = %f\n", CPG_Result.dual->d783);
  printf("d784 = %f\n", CPG_Result.dual->d784);
  printf("d785 = %f\n", CPG_Result.dual->d785);
  printf("d786 = %f\n", CPG_Result.dual->d786);
  printf("d787 = %f\n", CPG_Result.dual->d787);
  printf("d788 = %f\n", CPG_Result.dual->d788);
  printf("d789 = %f\n", CPG_Result.dual->d789);
  printf("d790 = %f\n", CPG_Result.dual->d790);
  for(i=0; i<3; i++) {
    printf("d791[%d] = %f\n", i, CPG_Result.dual->d791[i]);
  }
  for(i=0; i<3; i++) {
    printf("d792[%d] = %f\n", i, CPG_Result.dual->d792[i]);
  }
  printf("d793 = %f\n", CPG_Result.dual->d793);
  printf("d794 = %f\n", CPG_Result.dual->d794);
  printf("d795 = %f\n", CPG_Result.dual->d795);
  printf("d796 = %f\n", CPG_Result.dual->d796);
  printf("d797 = %f\n", CPG_Result.dual->d797);
  printf("d798 = %f\n", CPG_Result.dual->d798);
  printf("d799 = %f\n", CPG_Result.dual->d799);
  printf("d800 = %f\n", CPG_Result.dual->d800);
  printf("d801 = %f\n", CPG_Result.dual->d801);
  for(i=0; i<3; i++) {
    printf("d802[%d] = %f\n", i, CPG_Result.dual->d802[i]);
  }
  for(i=0; i<3; i++) {
    printf("d803[%d] = %f\n", i, CPG_Result.dual->d803[i]);
  }
  printf("d804 = %f\n", CPG_Result.dual->d804);
  printf("d805 = %f\n", CPG_Result.dual->d805);
  printf("d806 = %f\n", CPG_Result.dual->d806);
  printf("d807 = %f\n", CPG_Result.dual->d807);
  printf("d808 = %f\n", CPG_Result.dual->d808);
  printf("d809 = %f\n", CPG_Result.dual->d809);
  printf("d810 = %f\n", CPG_Result.dual->d810);
  printf("d811 = %f\n", CPG_Result.dual->d811);
  printf("d812 = %f\n", CPG_Result.dual->d812);
  for(i=0; i<3; i++) {
    printf("d813[%d] = %f\n", i, CPG_Result.dual->d813[i]);
  }
  for(i=0; i<3; i++) {
    printf("d814[%d] = %f\n", i, CPG_Result.dual->d814[i]);
  }
  printf("d815 = %f\n", CPG_Result.dual->d815);
  printf("d816 = %f\n", CPG_Result.dual->d816);
  printf("d817 = %f\n", CPG_Result.dual->d817);
  printf("d818 = %f\n", CPG_Result.dual->d818);
  printf("d819 = %f\n", CPG_Result.dual->d819);
  printf("d820 = %f\n", CPG_Result.dual->d820);
  printf("d821 = %f\n", CPG_Result.dual->d821);
  printf("d822 = %f\n", CPG_Result.dual->d822);
  printf("d823 = %f\n", CPG_Result.dual->d823);
  for(i=0; i<3; i++) {
    printf("d824[%d] = %f\n", i, CPG_Result.dual->d824[i]);
  }
  for(i=0; i<3; i++) {
    printf("d825[%d] = %f\n", i, CPG_Result.dual->d825[i]);
  }
  printf("d826 = %f\n", CPG_Result.dual->d826);
  printf("d827 = %f\n", CPG_Result.dual->d827);
  printf("d828 = %f\n", CPG_Result.dual->d828);
  printf("d829 = %f\n", CPG_Result.dual->d829);
  printf("d830 = %f\n", CPG_Result.dual->d830);
  printf("d831 = %f\n", CPG_Result.dual->d831);
  printf("d832 = %f\n", CPG_Result.dual->d832);
  printf("d833 = %f\n", CPG_Result.dual->d833);
  printf("d834 = %f\n", CPG_Result.dual->d834);
  for(i=0; i<3; i++) {
    printf("d835[%d] = %f\n", i, CPG_Result.dual->d835[i]);
  }
  for(i=0; i<3; i++) {
    printf("d836[%d] = %f\n", i, CPG_Result.dual->d836[i]);
  }
  printf("d837 = %f\n", CPG_Result.dual->d837);
  printf("d838 = %f\n", CPG_Result.dual->d838);
  printf("d839 = %f\n", CPG_Result.dual->d839);
  printf("d840 = %f\n", CPG_Result.dual->d840);
  printf("d841 = %f\n", CPG_Result.dual->d841);
  printf("d842 = %f\n", CPG_Result.dual->d842);
  printf("d843 = %f\n", CPG_Result.dual->d843);
  printf("d844 = %f\n", CPG_Result.dual->d844);
  printf("d845 = %f\n", CPG_Result.dual->d845);
  for(i=0; i<3; i++) {
    printf("d846[%d] = %f\n", i, CPG_Result.dual->d846[i]);
  }
  for(i=0; i<3; i++) {
    printf("d847[%d] = %f\n", i, CPG_Result.dual->d847[i]);
  }
  printf("d848 = %f\n", CPG_Result.dual->d848);
  printf("d849 = %f\n", CPG_Result.dual->d849);
  printf("d850 = %f\n", CPG_Result.dual->d850);
  printf("d851 = %f\n", CPG_Result.dual->d851);
  printf("d852 = %f\n", CPG_Result.dual->d852);
  printf("d853 = %f\n", CPG_Result.dual->d853);
  printf("d854 = %f\n", CPG_Result.dual->d854);
  printf("d855 = %f\n", CPG_Result.dual->d855);
  printf("d856 = %f\n", CPG_Result.dual->d856);
  for(i=0; i<3; i++) {
    printf("d857[%d] = %f\n", i, CPG_Result.dual->d857[i]);
  }
  for(i=0; i<3; i++) {
    printf("d858[%d] = %f\n", i, CPG_Result.dual->d858[i]);
  }
  printf("d859 = %f\n", CPG_Result.dual->d859);
  printf("d860 = %f\n", CPG_Result.dual->d860);
  printf("d861 = %f\n", CPG_Result.dual->d861);
  printf("d862 = %f\n", CPG_Result.dual->d862);
  printf("d863 = %f\n", CPG_Result.dual->d863);
  printf("d864 = %f\n", CPG_Result.dual->d864);
  printf("d865 = %f\n", CPG_Result.dual->d865);
  printf("d866 = %f\n", CPG_Result.dual->d866);
  printf("d867 = %f\n", CPG_Result.dual->d867);
  for(i=0; i<3; i++) {
    printf("d868[%d] = %f\n", i, CPG_Result.dual->d868[i]);
  }
  for(i=0; i<3; i++) {
    printf("d869[%d] = %f\n", i, CPG_Result.dual->d869[i]);
  }
  printf("d870 = %f\n", CPG_Result.dual->d870);
  printf("d871 = %f\n", CPG_Result.dual->d871);
  printf("d872 = %f\n", CPG_Result.dual->d872);
  printf("d873 = %f\n", CPG_Result.dual->d873);
  printf("d874 = %f\n", CPG_Result.dual->d874);
  printf("d875 = %f\n", CPG_Result.dual->d875);
  printf("d876 = %f\n", CPG_Result.dual->d876);
  printf("d877 = %f\n", CPG_Result.dual->d877);
  printf("d878 = %f\n", CPG_Result.dual->d878);
  for(i=0; i<3; i++) {
    printf("d879[%d] = %f\n", i, CPG_Result.dual->d879[i]);
  }
  for(i=0; i<3; i++) {
    printf("d880[%d] = %f\n", i, CPG_Result.dual->d880[i]);
  }
  printf("d881 = %f\n", CPG_Result.dual->d881);
  printf("d882 = %f\n", CPG_Result.dual->d882);
  printf("d883 = %f\n", CPG_Result.dual->d883);
  printf("d884 = %f\n", CPG_Result.dual->d884);
  printf("d885 = %f\n", CPG_Result.dual->d885);
  printf("d886 = %f\n", CPG_Result.dual->d886);
  printf("d887 = %f\n", CPG_Result.dual->d887);
  printf("d888 = %f\n", CPG_Result.dual->d888);
  printf("d889 = %f\n", CPG_Result.dual->d889);
  for(i=0; i<3; i++) {
    printf("d890[%d] = %f\n", i, CPG_Result.dual->d890[i]);
  }
  for(i=0; i<3; i++) {
    printf("d891[%d] = %f\n", i, CPG_Result.dual->d891[i]);
  }
  printf("d892 = %f\n", CPG_Result.dual->d892);
  printf("d893 = %f\n", CPG_Result.dual->d893);
  printf("d894 = %f\n", CPG_Result.dual->d894);
  printf("d895 = %f\n", CPG_Result.dual->d895);
  printf("d896 = %f\n", CPG_Result.dual->d896);
  printf("d897 = %f\n", CPG_Result.dual->d897);
  printf("d898 = %f\n", CPG_Result.dual->d898);
  printf("d899 = %f\n", CPG_Result.dual->d899);
  printf("d900 = %f\n", CPG_Result.dual->d900);
  for(i=0; i<3; i++) {
    printf("d901[%d] = %f\n", i, CPG_Result.dual->d901[i]);
  }
  for(i=0; i<3; i++) {
    printf("d902[%d] = %f\n", i, CPG_Result.dual->d902[i]);
  }
  printf("d903 = %f\n", CPG_Result.dual->d903);
  printf("d904 = %f\n", CPG_Result.dual->d904);
  printf("d905 = %f\n", CPG_Result.dual->d905);
  printf("d906 = %f\n", CPG_Result.dual->d906);
  printf("d907 = %f\n", CPG_Result.dual->d907);
  printf("d908 = %f\n", CPG_Result.dual->d908);
  printf("d909 = %f\n", CPG_Result.dual->d909);
  printf("d910 = %f\n", CPG_Result.dual->d910);
  printf("d911 = %f\n", CPG_Result.dual->d911);
  for(i=0; i<3; i++) {
    printf("d912[%d] = %f\n", i, CPG_Result.dual->d912[i]);
  }
  for(i=0; i<3; i++) {
    printf("d913[%d] = %f\n", i, CPG_Result.dual->d913[i]);
  }
  printf("d914 = %f\n", CPG_Result.dual->d914);
  printf("d915 = %f\n", CPG_Result.dual->d915);
  printf("d916 = %f\n", CPG_Result.dual->d916);
  printf("d917 = %f\n", CPG_Result.dual->d917);
  printf("d918 = %f\n", CPG_Result.dual->d918);
  printf("d919 = %f\n", CPG_Result.dual->d919);
  printf("d920 = %f\n", CPG_Result.dual->d920);
  printf("d921 = %f\n", CPG_Result.dual->d921);
  printf("d922 = %f\n", CPG_Result.dual->d922);
  for(i=0; i<3; i++) {
    printf("d923[%d] = %f\n", i, CPG_Result.dual->d923[i]);
  }
  for(i=0; i<3; i++) {
    printf("d924[%d] = %f\n", i, CPG_Result.dual->d924[i]);
  }
  printf("d925 = %f\n", CPG_Result.dual->d925);
  printf("d926 = %f\n", CPG_Result.dual->d926);
  printf("d927 = %f\n", CPG_Result.dual->d927);
  printf("d928 = %f\n", CPG_Result.dual->d928);
  printf("d929 = %f\n", CPG_Result.dual->d929);
  printf("d930 = %f\n", CPG_Result.dual->d930);
  printf("d931 = %f\n", CPG_Result.dual->d931);
  printf("d932 = %f\n", CPG_Result.dual->d932);
  printf("d933 = %f\n", CPG_Result.dual->d933);
  for(i=0; i<3; i++) {
    printf("d934[%d] = %f\n", i, CPG_Result.dual->d934[i]);
  }
  for(i=0; i<3; i++) {
    printf("d935[%d] = %f\n", i, CPG_Result.dual->d935[i]);
  }
  printf("d936 = %f\n", CPG_Result.dual->d936);
  printf("d937 = %f\n", CPG_Result.dual->d937);
  printf("d938 = %f\n", CPG_Result.dual->d938);
  printf("d939 = %f\n", CPG_Result.dual->d939);
  printf("d940 = %f\n", CPG_Result.dual->d940);
  printf("d941 = %f\n", CPG_Result.dual->d941);
  printf("d942 = %f\n", CPG_Result.dual->d942);
  printf("d943 = %f\n", CPG_Result.dual->d943);
  printf("d944 = %f\n", CPG_Result.dual->d944);
  for(i=0; i<3; i++) {
    printf("d945[%d] = %f\n", i, CPG_Result.dual->d945[i]);
  }
  for(i=0; i<3; i++) {
    printf("d946[%d] = %f\n", i, CPG_Result.dual->d946[i]);
  }
  printf("d947 = %f\n", CPG_Result.dual->d947);
  printf("d948 = %f\n", CPG_Result.dual->d948);
  printf("d949 = %f\n", CPG_Result.dual->d949);
  printf("d950 = %f\n", CPG_Result.dual->d950);
  printf("d951 = %f\n", CPG_Result.dual->d951);
  printf("d952 = %f\n", CPG_Result.dual->d952);
  printf("d953 = %f\n", CPG_Result.dual->d953);
  printf("d954 = %f\n", CPG_Result.dual->d954);
  printf("d955 = %f\n", CPG_Result.dual->d955);
  for(i=0; i<3; i++) {
    printf("d956[%d] = %f\n", i, CPG_Result.dual->d956[i]);
  }
  for(i=0; i<3; i++) {
    printf("d957[%d] = %f\n", i, CPG_Result.dual->d957[i]);
  }
  printf("d958 = %f\n", CPG_Result.dual->d958);
  printf("d959 = %f\n", CPG_Result.dual->d959);
  printf("d960 = %f\n", CPG_Result.dual->d960);
  printf("d961 = %f\n", CPG_Result.dual->d961);
  printf("d962 = %f\n", CPG_Result.dual->d962);
  printf("d963 = %f\n", CPG_Result.dual->d963);
  printf("d964 = %f\n", CPG_Result.dual->d964);
  printf("d965 = %f\n", CPG_Result.dual->d965);
  printf("d966 = %f\n", CPG_Result.dual->d966);
  for(i=0; i<3; i++) {
    printf("d967[%d] = %f\n", i, CPG_Result.dual->d967[i]);
  }
  for(i=0; i<3; i++) {
    printf("d968[%d] = %f\n", i, CPG_Result.dual->d968[i]);
  }
  printf("d969 = %f\n", CPG_Result.dual->d969);
  printf("d970 = %f\n", CPG_Result.dual->d970);
  printf("d971 = %f\n", CPG_Result.dual->d971);
  printf("d972 = %f\n", CPG_Result.dual->d972);
  printf("d973 = %f\n", CPG_Result.dual->d973);
  printf("d974 = %f\n", CPG_Result.dual->d974);
  printf("d975 = %f\n", CPG_Result.dual->d975);
  printf("d976 = %f\n", CPG_Result.dual->d976);
  printf("d977 = %f\n", CPG_Result.dual->d977);
  for(i=0; i<3; i++) {
    printf("d978[%d] = %f\n", i, CPG_Result.dual->d978[i]);
  }
  for(i=0; i<3; i++) {
    printf("d979[%d] = %f\n", i, CPG_Result.dual->d979[i]);
  }
  printf("d980 = %f\n", CPG_Result.dual->d980);
  printf("d981 = %f\n", CPG_Result.dual->d981);
  printf("d982 = %f\n", CPG_Result.dual->d982);
  printf("d983 = %f\n", CPG_Result.dual->d983);
  printf("d984 = %f\n", CPG_Result.dual->d984);
  printf("d985 = %f\n", CPG_Result.dual->d985);
  printf("d986 = %f\n", CPG_Result.dual->d986);
  printf("d987 = %f\n", CPG_Result.dual->d987);
  printf("d988 = %f\n", CPG_Result.dual->d988);
  for(i=0; i<3; i++) {
    printf("d989[%d] = %f\n", i, CPG_Result.dual->d989[i]);
  }
  for(i=0; i<3; i++) {
    printf("d990[%d] = %f\n", i, CPG_Result.dual->d990[i]);
  }
  printf("d991 = %f\n", CPG_Result.dual->d991);
  printf("d992 = %f\n", CPG_Result.dual->d992);
  printf("d993 = %f\n", CPG_Result.dual->d993);
  printf("d994 = %f\n", CPG_Result.dual->d994);
  printf("d995 = %f\n", CPG_Result.dual->d995);
  printf("d996 = %f\n", CPG_Result.dual->d996);
  printf("d997 = %f\n", CPG_Result.dual->d997);
  printf("d998 = %f\n", CPG_Result.dual->d998);
  printf("d999 = %f\n", CPG_Result.dual->d999);
  for(i=0; i<3; i++) {
    printf("d1000[%d] = %f\n", i, CPG_Result.dual->d1000[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1001[%d] = %f\n", i, CPG_Result.dual->d1001[i]);
  }
  printf("d1002 = %f\n", CPG_Result.dual->d1002);
  printf("d1003 = %f\n", CPG_Result.dual->d1003);
  printf("d1004 = %f\n", CPG_Result.dual->d1004);
  printf("d1005 = %f\n", CPG_Result.dual->d1005);
  printf("d1006 = %f\n", CPG_Result.dual->d1006);
  printf("d1007 = %f\n", CPG_Result.dual->d1007);
  printf("d1008 = %f\n", CPG_Result.dual->d1008);
  printf("d1009 = %f\n", CPG_Result.dual->d1009);
  printf("d1010 = %f\n", CPG_Result.dual->d1010);
  for(i=0; i<3; i++) {
    printf("d1011[%d] = %f\n", i, CPG_Result.dual->d1011[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1012[%d] = %f\n", i, CPG_Result.dual->d1012[i]);
  }
  printf("d1013 = %f\n", CPG_Result.dual->d1013);
  printf("d1014 = %f\n", CPG_Result.dual->d1014);
  printf("d1015 = %f\n", CPG_Result.dual->d1015);
  printf("d1016 = %f\n", CPG_Result.dual->d1016);
  printf("d1017 = %f\n", CPG_Result.dual->d1017);
  printf("d1018 = %f\n", CPG_Result.dual->d1018);
  printf("d1019 = %f\n", CPG_Result.dual->d1019);
  printf("d1020 = %f\n", CPG_Result.dual->d1020);
  printf("d1021 = %f\n", CPG_Result.dual->d1021);
  for(i=0; i<3; i++) {
    printf("d1022[%d] = %f\n", i, CPG_Result.dual->d1022[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1023[%d] = %f\n", i, CPG_Result.dual->d1023[i]);
  }
  printf("d1024 = %f\n", CPG_Result.dual->d1024);
  printf("d1025 = %f\n", CPG_Result.dual->d1025);
  printf("d1026 = %f\n", CPG_Result.dual->d1026);
  printf("d1027 = %f\n", CPG_Result.dual->d1027);
  printf("d1028 = %f\n", CPG_Result.dual->d1028);
  printf("d1029 = %f\n", CPG_Result.dual->d1029);
  printf("d1030 = %f\n", CPG_Result.dual->d1030);
  printf("d1031 = %f\n", CPG_Result.dual->d1031);
  printf("d1032 = %f\n", CPG_Result.dual->d1032);
  for(i=0; i<3; i++) {
    printf("d1033[%d] = %f\n", i, CPG_Result.dual->d1033[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1034[%d] = %f\n", i, CPG_Result.dual->d1034[i]);
  }
  printf("d1035 = %f\n", CPG_Result.dual->d1035);
  printf("d1036 = %f\n", CPG_Result.dual->d1036);
  printf("d1037 = %f\n", CPG_Result.dual->d1037);
  printf("d1038 = %f\n", CPG_Result.dual->d1038);
  printf("d1039 = %f\n", CPG_Result.dual->d1039);
  printf("d1040 = %f\n", CPG_Result.dual->d1040);
  printf("d1041 = %f\n", CPG_Result.dual->d1041);
  printf("d1042 = %f\n", CPG_Result.dual->d1042);
  printf("d1043 = %f\n", CPG_Result.dual->d1043);
  for(i=0; i<3; i++) {
    printf("d1044[%d] = %f\n", i, CPG_Result.dual->d1044[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1045[%d] = %f\n", i, CPG_Result.dual->d1045[i]);
  }
  printf("d1046 = %f\n", CPG_Result.dual->d1046);
  printf("d1047 = %f\n", CPG_Result.dual->d1047);
  printf("d1048 = %f\n", CPG_Result.dual->d1048);
  printf("d1049 = %f\n", CPG_Result.dual->d1049);
  printf("d1050 = %f\n", CPG_Result.dual->d1050);
  printf("d1051 = %f\n", CPG_Result.dual->d1051);
  printf("d1052 = %f\n", CPG_Result.dual->d1052);
  printf("d1053 = %f\n", CPG_Result.dual->d1053);
  printf("d1054 = %f\n", CPG_Result.dual->d1054);
  for(i=0; i<3; i++) {
    printf("d1055[%d] = %f\n", i, CPG_Result.dual->d1055[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1056[%d] = %f\n", i, CPG_Result.dual->d1056[i]);
  }
  printf("d1057 = %f\n", CPG_Result.dual->d1057);
  printf("d1058 = %f\n", CPG_Result.dual->d1058);
  printf("d1059 = %f\n", CPG_Result.dual->d1059);
  printf("d1060 = %f\n", CPG_Result.dual->d1060);
  printf("d1061 = %f\n", CPG_Result.dual->d1061);
  printf("d1062 = %f\n", CPG_Result.dual->d1062);
  printf("d1063 = %f\n", CPG_Result.dual->d1063);
  printf("d1064 = %f\n", CPG_Result.dual->d1064);
  printf("d1065 = %f\n", CPG_Result.dual->d1065);
  for(i=0; i<3; i++) {
    printf("d1066[%d] = %f\n", i, CPG_Result.dual->d1066[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1067[%d] = %f\n", i, CPG_Result.dual->d1067[i]);
  }
  printf("d1068 = %f\n", CPG_Result.dual->d1068);
  printf("d1069 = %f\n", CPG_Result.dual->d1069);
  printf("d1070 = %f\n", CPG_Result.dual->d1070);
  printf("d1071 = %f\n", CPG_Result.dual->d1071);
  printf("d1072 = %f\n", CPG_Result.dual->d1072);
  printf("d1073 = %f\n", CPG_Result.dual->d1073);
  printf("d1074 = %f\n", CPG_Result.dual->d1074);
  printf("d1075 = %f\n", CPG_Result.dual->d1075);
  printf("d1076 = %f\n", CPG_Result.dual->d1076);
  for(i=0; i<3; i++) {
    printf("d1077[%d] = %f\n", i, CPG_Result.dual->d1077[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1078[%d] = %f\n", i, CPG_Result.dual->d1078[i]);
  }
  printf("d1079 = %f\n", CPG_Result.dual->d1079);
  printf("d1080 = %f\n", CPG_Result.dual->d1080);
  printf("d1081 = %f\n", CPG_Result.dual->d1081);
  printf("d1082 = %f\n", CPG_Result.dual->d1082);
  printf("d1083 = %f\n", CPG_Result.dual->d1083);
  printf("d1084 = %f\n", CPG_Result.dual->d1084);
  printf("d1085 = %f\n", CPG_Result.dual->d1085);
  printf("d1086 = %f\n", CPG_Result.dual->d1086);
  printf("d1087 = %f\n", CPG_Result.dual->d1087);
  for(i=0; i<3; i++) {
    printf("d1088[%d] = %f\n", i, CPG_Result.dual->d1088[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1089[%d] = %f\n", i, CPG_Result.dual->d1089[i]);
  }
  printf("d1090 = %f\n", CPG_Result.dual->d1090);
  printf("d1091 = %f\n", CPG_Result.dual->d1091);
  printf("d1092 = %f\n", CPG_Result.dual->d1092);
  printf("d1093 = %f\n", CPG_Result.dual->d1093);
  printf("d1094 = %f\n", CPG_Result.dual->d1094);
  printf("d1095 = %f\n", CPG_Result.dual->d1095);
  printf("d1096 = %f\n", CPG_Result.dual->d1096);
  printf("d1097 = %f\n", CPG_Result.dual->d1097);
  printf("d1098 = %f\n", CPG_Result.dual->d1098);
  for(i=0; i<3; i++) {
    printf("d1099[%d] = %f\n", i, CPG_Result.dual->d1099[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1100[%d] = %f\n", i, CPG_Result.dual->d1100[i]);
  }
  printf("d1101 = %f\n", CPG_Result.dual->d1101);
  printf("d1102 = %f\n", CPG_Result.dual->d1102);
  printf("d1103 = %f\n", CPG_Result.dual->d1103);

  return 0;

}
