
/*
Auto-generated by CVXPYgen on January 14, 2026 at 23:02:01.
Content: Type definitions and variable declarations.
*/

#include "qoco.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

typedef QOCOFloat cpg_float;
typedef QOCOInt cpg_int;

// Compressed sparse column matrix
typedef struct {
  cpg_int      *p;
  cpg_int      *i;
  cpg_float    *x;
  cpg_int      nnz;
} cpg_csc;

// Canonical parameters
typedef struct {
  cpg_float    *c;         // Canonical parameter c
  cpg_float    d;          // Canonical parameter d
  cpg_csc      *A;         // Canonical parameter A
  cpg_float    *b;         // Canonical parameter b
  cpg_csc      *G;         // Canonical parameter G
  cpg_float    *h;         // Canonical parameter h
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        c;            // Bool, if canonical parameter c outdated
  int        d;            // Bool, if canonical parameter d outdated
  int        A;            // Bool, if canonical parameter A outdated
  int        b;            // Bool, if canonical parameter b outdated
  int        G;            // Bool, if canonical parameter G outdated
  int        h;            // Bool, if canonical parameter h outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  cpg_float    *z;         // Your variable z
  cpg_float    *x;         // Your variable x
  cpg_float    *u;         // Your variable u
  cpg_float    *s;         // Your variable s
} CPG_Prim_t;

// Dual solution
typedef struct {
  cpg_float    *d0;        // Your dual variable for constraint d0
  cpg_float    *d1;        // Your dual variable for constraint d1
  cpg_float    d2;         // Your dual variable for constraint d2
  cpg_float    d3;         // Your dual variable for constraint d3
  cpg_float    d4;         // Your dual variable for constraint d4
  cpg_float    d5;         // Your dual variable for constraint d5
  cpg_float    d6;         // Your dual variable for constraint d6
  cpg_float    d7;         // Your dual variable for constraint d7
  cpg_float    d8;         // Your dual variable for constraint d8
  cpg_float    d9;         // Your dual variable for constraint d9
  cpg_float    *d10;       // Your dual variable for constraint d10
  cpg_float    *d11;       // Your dual variable for constraint d11
  cpg_float    d12;        // Your dual variable for constraint d12
  cpg_float    d13;        // Your dual variable for constraint d13
  cpg_float    d14;        // Your dual variable for constraint d14
  cpg_float    d15;        // Your dual variable for constraint d15
  cpg_float    d16;        // Your dual variable for constraint d16
  cpg_float    d17;        // Your dual variable for constraint d17
  cpg_float    d18;        // Your dual variable for constraint d18
  cpg_float    d19;        // Your dual variable for constraint d19
  cpg_float    d20;        // Your dual variable for constraint d20
  cpg_float    *d21;       // Your dual variable for constraint d21
  cpg_float    *d22;       // Your dual variable for constraint d22
  cpg_float    d23;        // Your dual variable for constraint d23
  cpg_float    d24;        // Your dual variable for constraint d24
  cpg_float    d25;        // Your dual variable for constraint d25
  cpg_float    d26;        // Your dual variable for constraint d26
  cpg_float    d27;        // Your dual variable for constraint d27
  cpg_float    d28;        // Your dual variable for constraint d28
  cpg_float    d29;        // Your dual variable for constraint d29
  cpg_float    d30;        // Your dual variable for constraint d30
  cpg_float    d31;        // Your dual variable for constraint d31
  cpg_float    *d32;       // Your dual variable for constraint d32
  cpg_float    *d33;       // Your dual variable for constraint d33
  cpg_float    d34;        // Your dual variable for constraint d34
  cpg_float    d35;        // Your dual variable for constraint d35
  cpg_float    d36;        // Your dual variable for constraint d36
  cpg_float    d37;        // Your dual variable for constraint d37
  cpg_float    d38;        // Your dual variable for constraint d38
  cpg_float    d39;        // Your dual variable for constraint d39
  cpg_float    d40;        // Your dual variable for constraint d40
  cpg_float    d41;        // Your dual variable for constraint d41
  cpg_float    d42;        // Your dual variable for constraint d42
  cpg_float    *d43;       // Your dual variable for constraint d43
  cpg_float    *d44;       // Your dual variable for constraint d44
  cpg_float    d45;        // Your dual variable for constraint d45
  cpg_float    d46;        // Your dual variable for constraint d46
  cpg_float    d47;        // Your dual variable for constraint d47
  cpg_float    d48;        // Your dual variable for constraint d48
  cpg_float    d49;        // Your dual variable for constraint d49
  cpg_float    d50;        // Your dual variable for constraint d50
  cpg_float    d51;        // Your dual variable for constraint d51
  cpg_float    d52;        // Your dual variable for constraint d52
  cpg_float    d53;        // Your dual variable for constraint d53
  cpg_float    *d54;       // Your dual variable for constraint d54
  cpg_float    *d55;       // Your dual variable for constraint d55
  cpg_float    d56;        // Your dual variable for constraint d56
  cpg_float    d57;        // Your dual variable for constraint d57
  cpg_float    d58;        // Your dual variable for constraint d58
  cpg_float    d59;        // Your dual variable for constraint d59
  cpg_float    d60;        // Your dual variable for constraint d60
  cpg_float    d61;        // Your dual variable for constraint d61
  cpg_float    d62;        // Your dual variable for constraint d62
  cpg_float    d63;        // Your dual variable for constraint d63
  cpg_float    d64;        // Your dual variable for constraint d64
  cpg_float    *d65;       // Your dual variable for constraint d65
  cpg_float    *d66;       // Your dual variable for constraint d66
  cpg_float    d67;        // Your dual variable for constraint d67
  cpg_float    d68;        // Your dual variable for constraint d68
  cpg_float    d69;        // Your dual variable for constraint d69
  cpg_float    d70;        // Your dual variable for constraint d70
  cpg_float    d71;        // Your dual variable for constraint d71
  cpg_float    d72;        // Your dual variable for constraint d72
  cpg_float    d73;        // Your dual variable for constraint d73
  cpg_float    d74;        // Your dual variable for constraint d74
  cpg_float    d75;        // Your dual variable for constraint d75
  cpg_float    *d76;       // Your dual variable for constraint d76
  cpg_float    *d77;       // Your dual variable for constraint d77
  cpg_float    d78;        // Your dual variable for constraint d78
  cpg_float    d79;        // Your dual variable for constraint d79
  cpg_float    d80;        // Your dual variable for constraint d80
  cpg_float    d81;        // Your dual variable for constraint d81
  cpg_float    d82;        // Your dual variable for constraint d82
  cpg_float    d83;        // Your dual variable for constraint d83
  cpg_float    d84;        // Your dual variable for constraint d84
  cpg_float    d85;        // Your dual variable for constraint d85
  cpg_float    d86;        // Your dual variable for constraint d86
  cpg_float    *d87;       // Your dual variable for constraint d87
  cpg_float    *d88;       // Your dual variable for constraint d88
  cpg_float    d89;        // Your dual variable for constraint d89
  cpg_float    d90;        // Your dual variable for constraint d90
  cpg_float    d91;        // Your dual variable for constraint d91
  cpg_float    d92;        // Your dual variable for constraint d92
  cpg_float    d93;        // Your dual variable for constraint d93
  cpg_float    d94;        // Your dual variable for constraint d94
  cpg_float    d95;        // Your dual variable for constraint d95
  cpg_float    d96;        // Your dual variable for constraint d96
  cpg_float    d97;        // Your dual variable for constraint d97
  cpg_float    *d98;       // Your dual variable for constraint d98
  cpg_float    *d99;       // Your dual variable for constraint d99
  cpg_float    d100;       // Your dual variable for constraint d100
  cpg_float    d101;       // Your dual variable for constraint d101
  cpg_float    d102;       // Your dual variable for constraint d102
  cpg_float    d103;       // Your dual variable for constraint d103
  cpg_float    d104;       // Your dual variable for constraint d104
  cpg_float    d105;       // Your dual variable for constraint d105
  cpg_float    d106;       // Your dual variable for constraint d106
  cpg_float    d107;       // Your dual variable for constraint d107
  cpg_float    d108;       // Your dual variable for constraint d108
  cpg_float    *d109;      // Your dual variable for constraint d109
  cpg_float    *d110;      // Your dual variable for constraint d110
  cpg_float    d111;       // Your dual variable for constraint d111
  cpg_float    d112;       // Your dual variable for constraint d112
  cpg_float    d113;       // Your dual variable for constraint d113
  cpg_float    d114;       // Your dual variable for constraint d114
  cpg_float    d115;       // Your dual variable for constraint d115
  cpg_float    d116;       // Your dual variable for constraint d116
  cpg_float    d117;       // Your dual variable for constraint d117
  cpg_float    d118;       // Your dual variable for constraint d118
  cpg_float    d119;       // Your dual variable for constraint d119
  cpg_float    *d120;      // Your dual variable for constraint d120
  cpg_float    *d121;      // Your dual variable for constraint d121
  cpg_float    d122;       // Your dual variable for constraint d122
  cpg_float    d123;       // Your dual variable for constraint d123
  cpg_float    d124;       // Your dual variable for constraint d124
  cpg_float    d125;       // Your dual variable for constraint d125
  cpg_float    d126;       // Your dual variable for constraint d126
  cpg_float    d127;       // Your dual variable for constraint d127
  cpg_float    d128;       // Your dual variable for constraint d128
  cpg_float    d129;       // Your dual variable for constraint d129
  cpg_float    d130;       // Your dual variable for constraint d130
  cpg_float    *d131;      // Your dual variable for constraint d131
  cpg_float    *d132;      // Your dual variable for constraint d132
  cpg_float    d133;       // Your dual variable for constraint d133
  cpg_float    d134;       // Your dual variable for constraint d134
  cpg_float    d135;       // Your dual variable for constraint d135
  cpg_float    d136;       // Your dual variable for constraint d136
  cpg_float    d137;       // Your dual variable for constraint d137
  cpg_float    d138;       // Your dual variable for constraint d138
  cpg_float    d139;       // Your dual variable for constraint d139
  cpg_float    d140;       // Your dual variable for constraint d140
  cpg_float    d141;       // Your dual variable for constraint d141
  cpg_float    *d142;      // Your dual variable for constraint d142
  cpg_float    *d143;      // Your dual variable for constraint d143
  cpg_float    d144;       // Your dual variable for constraint d144
  cpg_float    d145;       // Your dual variable for constraint d145
  cpg_float    d146;       // Your dual variable for constraint d146
  cpg_float    d147;       // Your dual variable for constraint d147
  cpg_float    d148;       // Your dual variable for constraint d148
  cpg_float    d149;       // Your dual variable for constraint d149
  cpg_float    d150;       // Your dual variable for constraint d150
  cpg_float    d151;       // Your dual variable for constraint d151
  cpg_float    d152;       // Your dual variable for constraint d152
  cpg_float    *d153;      // Your dual variable for constraint d153
  cpg_float    *d154;      // Your dual variable for constraint d154
  cpg_float    d155;       // Your dual variable for constraint d155
  cpg_float    d156;       // Your dual variable for constraint d156
  cpg_float    d157;       // Your dual variable for constraint d157
  cpg_float    d158;       // Your dual variable for constraint d158
  cpg_float    d159;       // Your dual variable for constraint d159
  cpg_float    d160;       // Your dual variable for constraint d160
  cpg_float    d161;       // Your dual variable for constraint d161
  cpg_float    d162;       // Your dual variable for constraint d162
  cpg_float    d163;       // Your dual variable for constraint d163
  cpg_float    *d164;      // Your dual variable for constraint d164
  cpg_float    *d165;      // Your dual variable for constraint d165
  cpg_float    d166;       // Your dual variable for constraint d166
  cpg_float    d167;       // Your dual variable for constraint d167
  cpg_float    d168;       // Your dual variable for constraint d168
  cpg_float    d169;       // Your dual variable for constraint d169
  cpg_float    d170;       // Your dual variable for constraint d170
  cpg_float    d171;       // Your dual variable for constraint d171
  cpg_float    d172;       // Your dual variable for constraint d172
  cpg_float    d173;       // Your dual variable for constraint d173
  cpg_float    d174;       // Your dual variable for constraint d174
  cpg_float    *d175;      // Your dual variable for constraint d175
  cpg_float    *d176;      // Your dual variable for constraint d176
  cpg_float    d177;       // Your dual variable for constraint d177
  cpg_float    d178;       // Your dual variable for constraint d178
  cpg_float    d179;       // Your dual variable for constraint d179
  cpg_float    d180;       // Your dual variable for constraint d180
  cpg_float    d181;       // Your dual variable for constraint d181
  cpg_float    d182;       // Your dual variable for constraint d182
  cpg_float    d183;       // Your dual variable for constraint d183
  cpg_float    d184;       // Your dual variable for constraint d184
  cpg_float    d185;       // Your dual variable for constraint d185
  cpg_float    *d186;      // Your dual variable for constraint d186
  cpg_float    *d187;      // Your dual variable for constraint d187
  cpg_float    d188;       // Your dual variable for constraint d188
  cpg_float    d189;       // Your dual variable for constraint d189
  cpg_float    d190;       // Your dual variable for constraint d190
  cpg_float    d191;       // Your dual variable for constraint d191
  cpg_float    d192;       // Your dual variable for constraint d192
  cpg_float    d193;       // Your dual variable for constraint d193
  cpg_float    d194;       // Your dual variable for constraint d194
  cpg_float    d195;       // Your dual variable for constraint d195
  cpg_float    d196;       // Your dual variable for constraint d196
  cpg_float    *d197;      // Your dual variable for constraint d197
  cpg_float    *d198;      // Your dual variable for constraint d198
  cpg_float    d199;       // Your dual variable for constraint d199
  cpg_float    d200;       // Your dual variable for constraint d200
  cpg_float    d201;       // Your dual variable for constraint d201
  cpg_float    d202;       // Your dual variable for constraint d202
  cpg_float    d203;       // Your dual variable for constraint d203
  cpg_float    d204;       // Your dual variable for constraint d204
  cpg_float    d205;       // Your dual variable for constraint d205
  cpg_float    d206;       // Your dual variable for constraint d206
  cpg_float    d207;       // Your dual variable for constraint d207
  cpg_float    *d208;      // Your dual variable for constraint d208
  cpg_float    *d209;      // Your dual variable for constraint d209
  cpg_float    d210;       // Your dual variable for constraint d210
  cpg_float    d211;       // Your dual variable for constraint d211
  cpg_float    d212;       // Your dual variable for constraint d212
  cpg_float    d213;       // Your dual variable for constraint d213
  cpg_float    d214;       // Your dual variable for constraint d214
  cpg_float    d215;       // Your dual variable for constraint d215
  cpg_float    d216;       // Your dual variable for constraint d216
  cpg_float    d217;       // Your dual variable for constraint d217
  cpg_float    d218;       // Your dual variable for constraint d218
  cpg_float    *d219;      // Your dual variable for constraint d219
  cpg_float    *d220;      // Your dual variable for constraint d220
  cpg_float    d221;       // Your dual variable for constraint d221
  cpg_float    d222;       // Your dual variable for constraint d222
  cpg_float    d223;       // Your dual variable for constraint d223
  cpg_float    d224;       // Your dual variable for constraint d224
  cpg_float    d225;       // Your dual variable for constraint d225
  cpg_float    d226;       // Your dual variable for constraint d226
  cpg_float    d227;       // Your dual variable for constraint d227
  cpg_float    d228;       // Your dual variable for constraint d228
  cpg_float    d229;       // Your dual variable for constraint d229
  cpg_float    *d230;      // Your dual variable for constraint d230
  cpg_float    *d231;      // Your dual variable for constraint d231
  cpg_float    d232;       // Your dual variable for constraint d232
  cpg_float    d233;       // Your dual variable for constraint d233
  cpg_float    d234;       // Your dual variable for constraint d234
  cpg_float    d235;       // Your dual variable for constraint d235
  cpg_float    d236;       // Your dual variable for constraint d236
  cpg_float    d237;       // Your dual variable for constraint d237
  cpg_float    d238;       // Your dual variable for constraint d238
  cpg_float    d239;       // Your dual variable for constraint d239
  cpg_float    d240;       // Your dual variable for constraint d240
  cpg_float    *d241;      // Your dual variable for constraint d241
  cpg_float    *d242;      // Your dual variable for constraint d242
  cpg_float    d243;       // Your dual variable for constraint d243
  cpg_float    d244;       // Your dual variable for constraint d244
  cpg_float    d245;       // Your dual variable for constraint d245
  cpg_float    d246;       // Your dual variable for constraint d246
  cpg_float    d247;       // Your dual variable for constraint d247
  cpg_float    d248;       // Your dual variable for constraint d248
  cpg_float    d249;       // Your dual variable for constraint d249
  cpg_float    d250;       // Your dual variable for constraint d250
  cpg_float    d251;       // Your dual variable for constraint d251
  cpg_float    *d252;      // Your dual variable for constraint d252
  cpg_float    *d253;      // Your dual variable for constraint d253
  cpg_float    d254;       // Your dual variable for constraint d254
  cpg_float    d255;       // Your dual variable for constraint d255
  cpg_float    d256;       // Your dual variable for constraint d256
  cpg_float    d257;       // Your dual variable for constraint d257
  cpg_float    d258;       // Your dual variable for constraint d258
  cpg_float    d259;       // Your dual variable for constraint d259
  cpg_float    d260;       // Your dual variable for constraint d260
  cpg_float    d261;       // Your dual variable for constraint d261
  cpg_float    d262;       // Your dual variable for constraint d262
  cpg_float    *d263;      // Your dual variable for constraint d263
  cpg_float    *d264;      // Your dual variable for constraint d264
  cpg_float    d265;       // Your dual variable for constraint d265
  cpg_float    d266;       // Your dual variable for constraint d266
  cpg_float    d267;       // Your dual variable for constraint d267
  cpg_float    d268;       // Your dual variable for constraint d268
  cpg_float    d269;       // Your dual variable for constraint d269
  cpg_float    d270;       // Your dual variable for constraint d270
  cpg_float    d271;       // Your dual variable for constraint d271
  cpg_float    d272;       // Your dual variable for constraint d272
  cpg_float    d273;       // Your dual variable for constraint d273
  cpg_float    *d274;      // Your dual variable for constraint d274
  cpg_float    *d275;      // Your dual variable for constraint d275
  cpg_float    d276;       // Your dual variable for constraint d276
  cpg_float    d277;       // Your dual variable for constraint d277
  cpg_float    d278;       // Your dual variable for constraint d278
  cpg_float    d279;       // Your dual variable for constraint d279
  cpg_float    d280;       // Your dual variable for constraint d280
  cpg_float    d281;       // Your dual variable for constraint d281
  cpg_float    d282;       // Your dual variable for constraint d282
  cpg_float    d283;       // Your dual variable for constraint d283
  cpg_float    d284;       // Your dual variable for constraint d284
  cpg_float    *d285;      // Your dual variable for constraint d285
  cpg_float    *d286;      // Your dual variable for constraint d286
  cpg_float    d287;       // Your dual variable for constraint d287
  cpg_float    d288;       // Your dual variable for constraint d288
  cpg_float    d289;       // Your dual variable for constraint d289
  cpg_float    d290;       // Your dual variable for constraint d290
  cpg_float    d291;       // Your dual variable for constraint d291
  cpg_float    d292;       // Your dual variable for constraint d292
  cpg_float    d293;       // Your dual variable for constraint d293
  cpg_float    d294;       // Your dual variable for constraint d294
  cpg_float    d295;       // Your dual variable for constraint d295
  cpg_float    *d296;      // Your dual variable for constraint d296
  cpg_float    *d297;      // Your dual variable for constraint d297
  cpg_float    d298;       // Your dual variable for constraint d298
  cpg_float    d299;       // Your dual variable for constraint d299
  cpg_float    d300;       // Your dual variable for constraint d300
  cpg_float    d301;       // Your dual variable for constraint d301
  cpg_float    d302;       // Your dual variable for constraint d302
  cpg_float    d303;       // Your dual variable for constraint d303
  cpg_float    d304;       // Your dual variable for constraint d304
  cpg_float    d305;       // Your dual variable for constraint d305
  cpg_float    d306;       // Your dual variable for constraint d306
  cpg_float    *d307;      // Your dual variable for constraint d307
  cpg_float    *d308;      // Your dual variable for constraint d308
  cpg_float    d309;       // Your dual variable for constraint d309
  cpg_float    d310;       // Your dual variable for constraint d310
  cpg_float    d311;       // Your dual variable for constraint d311
  cpg_float    d312;       // Your dual variable for constraint d312
  cpg_float    d313;       // Your dual variable for constraint d313
  cpg_float    d314;       // Your dual variable for constraint d314
  cpg_float    d315;       // Your dual variable for constraint d315
  cpg_float    d316;       // Your dual variable for constraint d316
  cpg_float    d317;       // Your dual variable for constraint d317
  cpg_float    *d318;      // Your dual variable for constraint d318
  cpg_float    *d319;      // Your dual variable for constraint d319
  cpg_float    d320;       // Your dual variable for constraint d320
  cpg_float    d321;       // Your dual variable for constraint d321
  cpg_float    d322;       // Your dual variable for constraint d322
  cpg_float    d323;       // Your dual variable for constraint d323
  cpg_float    d324;       // Your dual variable for constraint d324
  cpg_float    d325;       // Your dual variable for constraint d325
  cpg_float    d326;       // Your dual variable for constraint d326
  cpg_float    d327;       // Your dual variable for constraint d327
  cpg_float    d328;       // Your dual variable for constraint d328
  cpg_float    *d329;      // Your dual variable for constraint d329
  cpg_float    *d330;      // Your dual variable for constraint d330
  cpg_float    d331;       // Your dual variable for constraint d331
  cpg_float    d332;       // Your dual variable for constraint d332
  cpg_float    d333;       // Your dual variable for constraint d333
  cpg_float    d334;       // Your dual variable for constraint d334
  cpg_float    d335;       // Your dual variable for constraint d335
  cpg_float    d336;       // Your dual variable for constraint d336
  cpg_float    d337;       // Your dual variable for constraint d337
  cpg_float    d338;       // Your dual variable for constraint d338
  cpg_float    d339;       // Your dual variable for constraint d339
  cpg_float    *d340;      // Your dual variable for constraint d340
  cpg_float    *d341;      // Your dual variable for constraint d341
  cpg_float    d342;       // Your dual variable for constraint d342
  cpg_float    d343;       // Your dual variable for constraint d343
  cpg_float    d344;       // Your dual variable for constraint d344
  cpg_float    d345;       // Your dual variable for constraint d345
  cpg_float    d346;       // Your dual variable for constraint d346
  cpg_float    d347;       // Your dual variable for constraint d347
  cpg_float    d348;       // Your dual variable for constraint d348
  cpg_float    d349;       // Your dual variable for constraint d349
  cpg_float    d350;       // Your dual variable for constraint d350
  cpg_float    *d351;      // Your dual variable for constraint d351
  cpg_float    *d352;      // Your dual variable for constraint d352
  cpg_float    d353;       // Your dual variable for constraint d353
  cpg_float    d354;       // Your dual variable for constraint d354
  cpg_float    d355;       // Your dual variable for constraint d355
  cpg_float    d356;       // Your dual variable for constraint d356
  cpg_float    d357;       // Your dual variable for constraint d357
  cpg_float    d358;       // Your dual variable for constraint d358
  cpg_float    d359;       // Your dual variable for constraint d359
  cpg_float    d360;       // Your dual variable for constraint d360
  cpg_float    d361;       // Your dual variable for constraint d361
  cpg_float    *d362;      // Your dual variable for constraint d362
  cpg_float    *d363;      // Your dual variable for constraint d363
  cpg_float    d364;       // Your dual variable for constraint d364
  cpg_float    d365;       // Your dual variable for constraint d365
  cpg_float    d366;       // Your dual variable for constraint d366
  cpg_float    d367;       // Your dual variable for constraint d367
  cpg_float    d368;       // Your dual variable for constraint d368
  cpg_float    d369;       // Your dual variable for constraint d369
  cpg_float    d370;       // Your dual variable for constraint d370
  cpg_float    d371;       // Your dual variable for constraint d371
  cpg_float    d372;       // Your dual variable for constraint d372
  cpg_float    *d373;      // Your dual variable for constraint d373
  cpg_float    *d374;      // Your dual variable for constraint d374
  cpg_float    d375;       // Your dual variable for constraint d375
  cpg_float    d376;       // Your dual variable for constraint d376
  cpg_float    d377;       // Your dual variable for constraint d377
  cpg_float    d378;       // Your dual variable for constraint d378
  cpg_float    d379;       // Your dual variable for constraint d379
  cpg_float    d380;       // Your dual variable for constraint d380
  cpg_float    d381;       // Your dual variable for constraint d381
  cpg_float    d382;       // Your dual variable for constraint d382
  cpg_float    d383;       // Your dual variable for constraint d383
  cpg_float    *d384;      // Your dual variable for constraint d384
  cpg_float    *d385;      // Your dual variable for constraint d385
  cpg_float    d386;       // Your dual variable for constraint d386
  cpg_float    d387;       // Your dual variable for constraint d387
  cpg_float    d388;       // Your dual variable for constraint d388
  cpg_float    d389;       // Your dual variable for constraint d389
  cpg_float    d390;       // Your dual variable for constraint d390
  cpg_float    d391;       // Your dual variable for constraint d391
  cpg_float    d392;       // Your dual variable for constraint d392
  cpg_float    d393;       // Your dual variable for constraint d393
  cpg_float    d394;       // Your dual variable for constraint d394
  cpg_float    *d395;      // Your dual variable for constraint d395
  cpg_float    *d396;      // Your dual variable for constraint d396
  cpg_float    d397;       // Your dual variable for constraint d397
  cpg_float    d398;       // Your dual variable for constraint d398
  cpg_float    d399;       // Your dual variable for constraint d399
  cpg_float    d400;       // Your dual variable for constraint d400
  cpg_float    d401;       // Your dual variable for constraint d401
  cpg_float    d402;       // Your dual variable for constraint d402
  cpg_float    d403;       // Your dual variable for constraint d403
  cpg_float    d404;       // Your dual variable for constraint d404
  cpg_float    d405;       // Your dual variable for constraint d405
  cpg_float    *d406;      // Your dual variable for constraint d406
  cpg_float    *d407;      // Your dual variable for constraint d407
  cpg_float    d408;       // Your dual variable for constraint d408
  cpg_float    d409;       // Your dual variable for constraint d409
  cpg_float    d410;       // Your dual variable for constraint d410
  cpg_float    d411;       // Your dual variable for constraint d411
  cpg_float    d412;       // Your dual variable for constraint d412
  cpg_float    d413;       // Your dual variable for constraint d413
  cpg_float    d414;       // Your dual variable for constraint d414
  cpg_float    d415;       // Your dual variable for constraint d415
  cpg_float    d416;       // Your dual variable for constraint d416
  cpg_float    *d417;      // Your dual variable for constraint d417
  cpg_float    *d418;      // Your dual variable for constraint d418
  cpg_float    d419;       // Your dual variable for constraint d419
  cpg_float    d420;       // Your dual variable for constraint d420
  cpg_float    d421;       // Your dual variable for constraint d421
  cpg_float    d422;       // Your dual variable for constraint d422
  cpg_float    d423;       // Your dual variable for constraint d423
  cpg_float    d424;       // Your dual variable for constraint d424
  cpg_float    d425;       // Your dual variable for constraint d425
  cpg_float    d426;       // Your dual variable for constraint d426
  cpg_float    d427;       // Your dual variable for constraint d427
  cpg_float    *d428;      // Your dual variable for constraint d428
  cpg_float    *d429;      // Your dual variable for constraint d429
  cpg_float    d430;       // Your dual variable for constraint d430
  cpg_float    d431;       // Your dual variable for constraint d431
  cpg_float    d432;       // Your dual variable for constraint d432
  cpg_float    d433;       // Your dual variable for constraint d433
  cpg_float    d434;       // Your dual variable for constraint d434
  cpg_float    d435;       // Your dual variable for constraint d435
  cpg_float    d436;       // Your dual variable for constraint d436
  cpg_float    d437;       // Your dual variable for constraint d437
  cpg_float    d438;       // Your dual variable for constraint d438
  cpg_float    *d439;      // Your dual variable for constraint d439
  cpg_float    *d440;      // Your dual variable for constraint d440
  cpg_float    d441;       // Your dual variable for constraint d441
  cpg_float    d442;       // Your dual variable for constraint d442
  cpg_float    d443;       // Your dual variable for constraint d443
  cpg_float    d444;       // Your dual variable for constraint d444
  cpg_float    d445;       // Your dual variable for constraint d445
  cpg_float    d446;       // Your dual variable for constraint d446
  cpg_float    d447;       // Your dual variable for constraint d447
  cpg_float    d448;       // Your dual variable for constraint d448
  cpg_float    d449;       // Your dual variable for constraint d449
  cpg_float    *d450;      // Your dual variable for constraint d450
  cpg_float    *d451;      // Your dual variable for constraint d451
  cpg_float    d452;       // Your dual variable for constraint d452
  cpg_float    d453;       // Your dual variable for constraint d453
  cpg_float    d454;       // Your dual variable for constraint d454
  cpg_float    d455;       // Your dual variable for constraint d455
  cpg_float    d456;       // Your dual variable for constraint d456
  cpg_float    d457;       // Your dual variable for constraint d457
  cpg_float    d458;       // Your dual variable for constraint d458
  cpg_float    d459;       // Your dual variable for constraint d459
  cpg_float    d460;       // Your dual variable for constraint d460
  cpg_float    *d461;      // Your dual variable for constraint d461
  cpg_float    *d462;      // Your dual variable for constraint d462
  cpg_float    d463;       // Your dual variable for constraint d463
  cpg_float    d464;       // Your dual variable for constraint d464
  cpg_float    d465;       // Your dual variable for constraint d465
  cpg_float    d466;       // Your dual variable for constraint d466
  cpg_float    d467;       // Your dual variable for constraint d467
  cpg_float    d468;       // Your dual variable for constraint d468
  cpg_float    d469;       // Your dual variable for constraint d469
  cpg_float    d470;       // Your dual variable for constraint d470
  cpg_float    d471;       // Your dual variable for constraint d471
  cpg_float    *d472;      // Your dual variable for constraint d472
  cpg_float    *d473;      // Your dual variable for constraint d473
  cpg_float    d474;       // Your dual variable for constraint d474
  cpg_float    d475;       // Your dual variable for constraint d475
  cpg_float    d476;       // Your dual variable for constraint d476
  cpg_float    d477;       // Your dual variable for constraint d477
  cpg_float    d478;       // Your dual variable for constraint d478
  cpg_float    d479;       // Your dual variable for constraint d479
  cpg_float    d480;       // Your dual variable for constraint d480
  cpg_float    d481;       // Your dual variable for constraint d481
  cpg_float    d482;       // Your dual variable for constraint d482
  cpg_float    *d483;      // Your dual variable for constraint d483
  cpg_float    *d484;      // Your dual variable for constraint d484
  cpg_float    d485;       // Your dual variable for constraint d485
  cpg_float    d486;       // Your dual variable for constraint d486
  cpg_float    d487;       // Your dual variable for constraint d487
  cpg_float    d488;       // Your dual variable for constraint d488
  cpg_float    d489;       // Your dual variable for constraint d489
  cpg_float    d490;       // Your dual variable for constraint d490
  cpg_float    d491;       // Your dual variable for constraint d491
  cpg_float    d492;       // Your dual variable for constraint d492
  cpg_float    d493;       // Your dual variable for constraint d493
  cpg_float    *d494;      // Your dual variable for constraint d494
  cpg_float    *d495;      // Your dual variable for constraint d495
  cpg_float    d496;       // Your dual variable for constraint d496
  cpg_float    d497;       // Your dual variable for constraint d497
  cpg_float    d498;       // Your dual variable for constraint d498
  cpg_float    d499;       // Your dual variable for constraint d499
  cpg_float    d500;       // Your dual variable for constraint d500
  cpg_float    d501;       // Your dual variable for constraint d501
  cpg_float    d502;       // Your dual variable for constraint d502
  cpg_float    d503;       // Your dual variable for constraint d503
  cpg_float    d504;       // Your dual variable for constraint d504
  cpg_float    *d505;      // Your dual variable for constraint d505
  cpg_float    *d506;      // Your dual variable for constraint d506
  cpg_float    d507;       // Your dual variable for constraint d507
  cpg_float    d508;       // Your dual variable for constraint d508
  cpg_float    d509;       // Your dual variable for constraint d509
  cpg_float    d510;       // Your dual variable for constraint d510
  cpg_float    d511;       // Your dual variable for constraint d511
  cpg_float    d512;       // Your dual variable for constraint d512
  cpg_float    d513;       // Your dual variable for constraint d513
  cpg_float    d514;       // Your dual variable for constraint d514
  cpg_float    d515;       // Your dual variable for constraint d515
  cpg_float    *d516;      // Your dual variable for constraint d516
  cpg_float    *d517;      // Your dual variable for constraint d517
  cpg_float    d518;       // Your dual variable for constraint d518
  cpg_float    d519;       // Your dual variable for constraint d519
  cpg_float    d520;       // Your dual variable for constraint d520
  cpg_float    d521;       // Your dual variable for constraint d521
  cpg_float    d522;       // Your dual variable for constraint d522
  cpg_float    d523;       // Your dual variable for constraint d523
  cpg_float    d524;       // Your dual variable for constraint d524
  cpg_float    d525;       // Your dual variable for constraint d525
  cpg_float    d526;       // Your dual variable for constraint d526
  cpg_float    *d527;      // Your dual variable for constraint d527
  cpg_float    *d528;      // Your dual variable for constraint d528
  cpg_float    d529;       // Your dual variable for constraint d529
  cpg_float    d530;       // Your dual variable for constraint d530
  cpg_float    d531;       // Your dual variable for constraint d531
  cpg_float    d532;       // Your dual variable for constraint d532
  cpg_float    d533;       // Your dual variable for constraint d533
  cpg_float    d534;       // Your dual variable for constraint d534
  cpg_float    d535;       // Your dual variable for constraint d535
  cpg_float    d536;       // Your dual variable for constraint d536
  cpg_float    d537;       // Your dual variable for constraint d537
  cpg_float    *d538;      // Your dual variable for constraint d538
  cpg_float    *d539;      // Your dual variable for constraint d539
  cpg_float    d540;       // Your dual variable for constraint d540
  cpg_float    d541;       // Your dual variable for constraint d541
  cpg_float    d542;       // Your dual variable for constraint d542
  cpg_float    d543;       // Your dual variable for constraint d543
  cpg_float    d544;       // Your dual variable for constraint d544
  cpg_float    d545;       // Your dual variable for constraint d545
  cpg_float    d546;       // Your dual variable for constraint d546
  cpg_float    d547;       // Your dual variable for constraint d547
  cpg_float    d548;       // Your dual variable for constraint d548
  cpg_float    *d549;      // Your dual variable for constraint d549
  cpg_float    *d550;      // Your dual variable for constraint d550
  cpg_float    d551;       // Your dual variable for constraint d551
  cpg_float    d552;       // Your dual variable for constraint d552
  cpg_float    d553;       // Your dual variable for constraint d553
  cpg_float    d554;       // Your dual variable for constraint d554
  cpg_float    d555;       // Your dual variable for constraint d555
  cpg_float    d556;       // Your dual variable for constraint d556
  cpg_float    d557;       // Your dual variable for constraint d557
  cpg_float    d558;       // Your dual variable for constraint d558
  cpg_float    d559;       // Your dual variable for constraint d559
  cpg_float    *d560;      // Your dual variable for constraint d560
  cpg_float    *d561;      // Your dual variable for constraint d561
  cpg_float    d562;       // Your dual variable for constraint d562
  cpg_float    d563;       // Your dual variable for constraint d563
  cpg_float    d564;       // Your dual variable for constraint d564
  cpg_float    d565;       // Your dual variable for constraint d565
  cpg_float    d566;       // Your dual variable for constraint d566
  cpg_float    d567;       // Your dual variable for constraint d567
  cpg_float    d568;       // Your dual variable for constraint d568
  cpg_float    d569;       // Your dual variable for constraint d569
  cpg_float    d570;       // Your dual variable for constraint d570
  cpg_float    *d571;      // Your dual variable for constraint d571
  cpg_float    *d572;      // Your dual variable for constraint d572
  cpg_float    d573;       // Your dual variable for constraint d573
  cpg_float    d574;       // Your dual variable for constraint d574
  cpg_float    d575;       // Your dual variable for constraint d575
  cpg_float    d576;       // Your dual variable for constraint d576
  cpg_float    d577;       // Your dual variable for constraint d577
  cpg_float    d578;       // Your dual variable for constraint d578
  cpg_float    d579;       // Your dual variable for constraint d579
  cpg_float    d580;       // Your dual variable for constraint d580
  cpg_float    d581;       // Your dual variable for constraint d581
  cpg_float    *d582;      // Your dual variable for constraint d582
  cpg_float    *d583;      // Your dual variable for constraint d583
  cpg_float    d584;       // Your dual variable for constraint d584
  cpg_float    d585;       // Your dual variable for constraint d585
  cpg_float    d586;       // Your dual variable for constraint d586
  cpg_float    d587;       // Your dual variable for constraint d587
  cpg_float    d588;       // Your dual variable for constraint d588
  cpg_float    d589;       // Your dual variable for constraint d589
  cpg_float    d590;       // Your dual variable for constraint d590
  cpg_float    d591;       // Your dual variable for constraint d591
  cpg_float    d592;       // Your dual variable for constraint d592
  cpg_float    *d593;      // Your dual variable for constraint d593
  cpg_float    *d594;      // Your dual variable for constraint d594
  cpg_float    d595;       // Your dual variable for constraint d595
  cpg_float    d596;       // Your dual variable for constraint d596
  cpg_float    d597;       // Your dual variable for constraint d597
  cpg_float    d598;       // Your dual variable for constraint d598
  cpg_float    d599;       // Your dual variable for constraint d599
  cpg_float    d600;       // Your dual variable for constraint d600
  cpg_float    d601;       // Your dual variable for constraint d601
  cpg_float    d602;       // Your dual variable for constraint d602
  cpg_float    d603;       // Your dual variable for constraint d603
  cpg_float    *d604;      // Your dual variable for constraint d604
  cpg_float    *d605;      // Your dual variable for constraint d605
  cpg_float    d606;       // Your dual variable for constraint d606
  cpg_float    d607;       // Your dual variable for constraint d607
  cpg_float    d608;       // Your dual variable for constraint d608
  cpg_float    d609;       // Your dual variable for constraint d609
  cpg_float    d610;       // Your dual variable for constraint d610
  cpg_float    d611;       // Your dual variable for constraint d611
  cpg_float    d612;       // Your dual variable for constraint d612
  cpg_float    d613;       // Your dual variable for constraint d613
  cpg_float    d614;       // Your dual variable for constraint d614
  cpg_float    *d615;      // Your dual variable for constraint d615
  cpg_float    *d616;      // Your dual variable for constraint d616
  cpg_float    d617;       // Your dual variable for constraint d617
  cpg_float    d618;       // Your dual variable for constraint d618
  cpg_float    d619;       // Your dual variable for constraint d619
  cpg_float    d620;       // Your dual variable for constraint d620
  cpg_float    d621;       // Your dual variable for constraint d621
  cpg_float    d622;       // Your dual variable for constraint d622
  cpg_float    d623;       // Your dual variable for constraint d623
  cpg_float    d624;       // Your dual variable for constraint d624
  cpg_float    d625;       // Your dual variable for constraint d625
  cpg_float    *d626;      // Your dual variable for constraint d626
  cpg_float    *d627;      // Your dual variable for constraint d627
  cpg_float    d628;       // Your dual variable for constraint d628
  cpg_float    d629;       // Your dual variable for constraint d629
  cpg_float    d630;       // Your dual variable for constraint d630
  cpg_float    d631;       // Your dual variable for constraint d631
  cpg_float    d632;       // Your dual variable for constraint d632
  cpg_float    d633;       // Your dual variable for constraint d633
  cpg_float    d634;       // Your dual variable for constraint d634
  cpg_float    d635;       // Your dual variable for constraint d635
  cpg_float    d636;       // Your dual variable for constraint d636
  cpg_float    *d637;      // Your dual variable for constraint d637
  cpg_float    *d638;      // Your dual variable for constraint d638
  cpg_float    d639;       // Your dual variable for constraint d639
  cpg_float    d640;       // Your dual variable for constraint d640
  cpg_float    d641;       // Your dual variable for constraint d641
  cpg_float    d642;       // Your dual variable for constraint d642
  cpg_float    d643;       // Your dual variable for constraint d643
  cpg_float    d644;       // Your dual variable for constraint d644
  cpg_float    d645;       // Your dual variable for constraint d645
  cpg_float    d646;       // Your dual variable for constraint d646
  cpg_float    d647;       // Your dual variable for constraint d647
  cpg_float    *d648;      // Your dual variable for constraint d648
  cpg_float    *d649;      // Your dual variable for constraint d649
  cpg_float    d650;       // Your dual variable for constraint d650
  cpg_float    d651;       // Your dual variable for constraint d651
  cpg_float    d652;       // Your dual variable for constraint d652
  cpg_float    d653;       // Your dual variable for constraint d653
  cpg_float    d654;       // Your dual variable for constraint d654
  cpg_float    d655;       // Your dual variable for constraint d655
  cpg_float    d656;       // Your dual variable for constraint d656
  cpg_float    d657;       // Your dual variable for constraint d657
  cpg_float    d658;       // Your dual variable for constraint d658
  cpg_float    *d659;      // Your dual variable for constraint d659
  cpg_float    *d660;      // Your dual variable for constraint d660
  cpg_float    d661;       // Your dual variable for constraint d661
  cpg_float    d662;       // Your dual variable for constraint d662
  cpg_float    d663;       // Your dual variable for constraint d663
  cpg_float    d664;       // Your dual variable for constraint d664
  cpg_float    d665;       // Your dual variable for constraint d665
  cpg_float    d666;       // Your dual variable for constraint d666
  cpg_float    d667;       // Your dual variable for constraint d667
  cpg_float    d668;       // Your dual variable for constraint d668
  cpg_float    d669;       // Your dual variable for constraint d669
  cpg_float    *d670;      // Your dual variable for constraint d670
  cpg_float    *d671;      // Your dual variable for constraint d671
  cpg_float    d672;       // Your dual variable for constraint d672
  cpg_float    d673;       // Your dual variable for constraint d673
  cpg_float    d674;       // Your dual variable for constraint d674
  cpg_float    d675;       // Your dual variable for constraint d675
  cpg_float    d676;       // Your dual variable for constraint d676
  cpg_float    d677;       // Your dual variable for constraint d677
  cpg_float    d678;       // Your dual variable for constraint d678
  cpg_float    d679;       // Your dual variable for constraint d679
  cpg_float    d680;       // Your dual variable for constraint d680
  cpg_float    *d681;      // Your dual variable for constraint d681
  cpg_float    *d682;      // Your dual variable for constraint d682
  cpg_float    d683;       // Your dual variable for constraint d683
  cpg_float    d684;       // Your dual variable for constraint d684
  cpg_float    d685;       // Your dual variable for constraint d685
  cpg_float    d686;       // Your dual variable for constraint d686
  cpg_float    d687;       // Your dual variable for constraint d687
  cpg_float    d688;       // Your dual variable for constraint d688
  cpg_float    d689;       // Your dual variable for constraint d689
  cpg_float    d690;       // Your dual variable for constraint d690
  cpg_float    d691;       // Your dual variable for constraint d691
  cpg_float    *d692;      // Your dual variable for constraint d692
  cpg_float    *d693;      // Your dual variable for constraint d693
  cpg_float    d694;       // Your dual variable for constraint d694
  cpg_float    d695;       // Your dual variable for constraint d695
  cpg_float    d696;       // Your dual variable for constraint d696
  cpg_float    d697;       // Your dual variable for constraint d697
  cpg_float    d698;       // Your dual variable for constraint d698
  cpg_float    d699;       // Your dual variable for constraint d699
  cpg_float    d700;       // Your dual variable for constraint d700
  cpg_float    d701;       // Your dual variable for constraint d701
  cpg_float    d702;       // Your dual variable for constraint d702
  cpg_float    *d703;      // Your dual variable for constraint d703
  cpg_float    *d704;      // Your dual variable for constraint d704
  cpg_float    d705;       // Your dual variable for constraint d705
  cpg_float    d706;       // Your dual variable for constraint d706
  cpg_float    d707;       // Your dual variable for constraint d707
  cpg_float    d708;       // Your dual variable for constraint d708
  cpg_float    d709;       // Your dual variable for constraint d709
  cpg_float    d710;       // Your dual variable for constraint d710
  cpg_float    d711;       // Your dual variable for constraint d711
  cpg_float    d712;       // Your dual variable for constraint d712
  cpg_float    d713;       // Your dual variable for constraint d713
  cpg_float    *d714;      // Your dual variable for constraint d714
  cpg_float    *d715;      // Your dual variable for constraint d715
  cpg_float    d716;       // Your dual variable for constraint d716
  cpg_float    d717;       // Your dual variable for constraint d717
  cpg_float    d718;       // Your dual variable for constraint d718
  cpg_float    d719;       // Your dual variable for constraint d719
  cpg_float    d720;       // Your dual variable for constraint d720
  cpg_float    d721;       // Your dual variable for constraint d721
  cpg_float    d722;       // Your dual variable for constraint d722
  cpg_float    d723;       // Your dual variable for constraint d723
  cpg_float    d724;       // Your dual variable for constraint d724
  cpg_float    *d725;      // Your dual variable for constraint d725
  cpg_float    *d726;      // Your dual variable for constraint d726
  cpg_float    d727;       // Your dual variable for constraint d727
  cpg_float    d728;       // Your dual variable for constraint d728
  cpg_float    d729;       // Your dual variable for constraint d729
  cpg_float    d730;       // Your dual variable for constraint d730
  cpg_float    d731;       // Your dual variable for constraint d731
  cpg_float    d732;       // Your dual variable for constraint d732
  cpg_float    d733;       // Your dual variable for constraint d733
  cpg_float    d734;       // Your dual variable for constraint d734
  cpg_float    d735;       // Your dual variable for constraint d735
  cpg_float    *d736;      // Your dual variable for constraint d736
  cpg_float    *d737;      // Your dual variable for constraint d737
  cpg_float    d738;       // Your dual variable for constraint d738
  cpg_float    d739;       // Your dual variable for constraint d739
  cpg_float    d740;       // Your dual variable for constraint d740
  cpg_float    d741;       // Your dual variable for constraint d741
  cpg_float    d742;       // Your dual variable for constraint d742
  cpg_float    d743;       // Your dual variable for constraint d743
  cpg_float    d744;       // Your dual variable for constraint d744
  cpg_float    d745;       // Your dual variable for constraint d745
  cpg_float    d746;       // Your dual variable for constraint d746
  cpg_float    *d747;      // Your dual variable for constraint d747
  cpg_float    *d748;      // Your dual variable for constraint d748
  cpg_float    d749;       // Your dual variable for constraint d749
  cpg_float    d750;       // Your dual variable for constraint d750
  cpg_float    d751;       // Your dual variable for constraint d751
  cpg_float    d752;       // Your dual variable for constraint d752
  cpg_float    d753;       // Your dual variable for constraint d753
  cpg_float    d754;       // Your dual variable for constraint d754
  cpg_float    d755;       // Your dual variable for constraint d755
  cpg_float    d756;       // Your dual variable for constraint d756
  cpg_float    d757;       // Your dual variable for constraint d757
  cpg_float    *d758;      // Your dual variable for constraint d758
  cpg_float    *d759;      // Your dual variable for constraint d759
  cpg_float    d760;       // Your dual variable for constraint d760
  cpg_float    d761;       // Your dual variable for constraint d761
  cpg_float    d762;       // Your dual variable for constraint d762
  cpg_float    d763;       // Your dual variable for constraint d763
  cpg_float    d764;       // Your dual variable for constraint d764
  cpg_float    d765;       // Your dual variable for constraint d765
  cpg_float    d766;       // Your dual variable for constraint d766
  cpg_float    d767;       // Your dual variable for constraint d767
  cpg_float    d768;       // Your dual variable for constraint d768
  cpg_float    *d769;      // Your dual variable for constraint d769
  cpg_float    *d770;      // Your dual variable for constraint d770
  cpg_float    d771;       // Your dual variable for constraint d771
  cpg_float    d772;       // Your dual variable for constraint d772
  cpg_float    d773;       // Your dual variable for constraint d773
  cpg_float    d774;       // Your dual variable for constraint d774
  cpg_float    d775;       // Your dual variable for constraint d775
  cpg_float    d776;       // Your dual variable for constraint d776
  cpg_float    d777;       // Your dual variable for constraint d777
  cpg_float    d778;       // Your dual variable for constraint d778
  cpg_float    d779;       // Your dual variable for constraint d779
  cpg_float    *d780;      // Your dual variable for constraint d780
  cpg_float    *d781;      // Your dual variable for constraint d781
  cpg_float    d782;       // Your dual variable for constraint d782
  cpg_float    d783;       // Your dual variable for constraint d783
  cpg_float    d784;       // Your dual variable for constraint d784
  cpg_float    d785;       // Your dual variable for constraint d785
  cpg_float    d786;       // Your dual variable for constraint d786
  cpg_float    d787;       // Your dual variable for constraint d787
  cpg_float    d788;       // Your dual variable for constraint d788
  cpg_float    d789;       // Your dual variable for constraint d789
  cpg_float    d790;       // Your dual variable for constraint d790
  cpg_float    *d791;      // Your dual variable for constraint d791
  cpg_float    *d792;      // Your dual variable for constraint d792
  cpg_float    d793;       // Your dual variable for constraint d793
  cpg_float    d794;       // Your dual variable for constraint d794
  cpg_float    d795;       // Your dual variable for constraint d795
  cpg_float    d796;       // Your dual variable for constraint d796
  cpg_float    d797;       // Your dual variable for constraint d797
  cpg_float    d798;       // Your dual variable for constraint d798
  cpg_float    d799;       // Your dual variable for constraint d799
  cpg_float    d800;       // Your dual variable for constraint d800
  cpg_float    d801;       // Your dual variable for constraint d801
  cpg_float    *d802;      // Your dual variable for constraint d802
  cpg_float    *d803;      // Your dual variable for constraint d803
  cpg_float    d804;       // Your dual variable for constraint d804
  cpg_float    d805;       // Your dual variable for constraint d805
  cpg_float    d806;       // Your dual variable for constraint d806
  cpg_float    d807;       // Your dual variable for constraint d807
  cpg_float    d808;       // Your dual variable for constraint d808
  cpg_float    d809;       // Your dual variable for constraint d809
  cpg_float    d810;       // Your dual variable for constraint d810
  cpg_float    d811;       // Your dual variable for constraint d811
  cpg_float    d812;       // Your dual variable for constraint d812
  cpg_float    *d813;      // Your dual variable for constraint d813
  cpg_float    *d814;      // Your dual variable for constraint d814
  cpg_float    d815;       // Your dual variable for constraint d815
  cpg_float    d816;       // Your dual variable for constraint d816
  cpg_float    d817;       // Your dual variable for constraint d817
  cpg_float    d818;       // Your dual variable for constraint d818
  cpg_float    d819;       // Your dual variable for constraint d819
  cpg_float    d820;       // Your dual variable for constraint d820
  cpg_float    d821;       // Your dual variable for constraint d821
  cpg_float    d822;       // Your dual variable for constraint d822
  cpg_float    d823;       // Your dual variable for constraint d823
  cpg_float    *d824;      // Your dual variable for constraint d824
  cpg_float    *d825;      // Your dual variable for constraint d825
  cpg_float    d826;       // Your dual variable for constraint d826
  cpg_float    d827;       // Your dual variable for constraint d827
  cpg_float    d828;       // Your dual variable for constraint d828
  cpg_float    d829;       // Your dual variable for constraint d829
  cpg_float    d830;       // Your dual variable for constraint d830
  cpg_float    d831;       // Your dual variable for constraint d831
  cpg_float    d832;       // Your dual variable for constraint d832
  cpg_float    d833;       // Your dual variable for constraint d833
  cpg_float    d834;       // Your dual variable for constraint d834
  cpg_float    *d835;      // Your dual variable for constraint d835
  cpg_float    *d836;      // Your dual variable for constraint d836
  cpg_float    d837;       // Your dual variable for constraint d837
  cpg_float    d838;       // Your dual variable for constraint d838
  cpg_float    d839;       // Your dual variable for constraint d839
  cpg_float    d840;       // Your dual variable for constraint d840
  cpg_float    d841;       // Your dual variable for constraint d841
  cpg_float    d842;       // Your dual variable for constraint d842
  cpg_float    d843;       // Your dual variable for constraint d843
  cpg_float    d844;       // Your dual variable for constraint d844
  cpg_float    d845;       // Your dual variable for constraint d845
  cpg_float    *d846;      // Your dual variable for constraint d846
  cpg_float    *d847;      // Your dual variable for constraint d847
  cpg_float    d848;       // Your dual variable for constraint d848
  cpg_float    d849;       // Your dual variable for constraint d849
  cpg_float    d850;       // Your dual variable for constraint d850
  cpg_float    d851;       // Your dual variable for constraint d851
  cpg_float    d852;       // Your dual variable for constraint d852
  cpg_float    d853;       // Your dual variable for constraint d853
  cpg_float    d854;       // Your dual variable for constraint d854
  cpg_float    d855;       // Your dual variable for constraint d855
  cpg_float    d856;       // Your dual variable for constraint d856
  cpg_float    *d857;      // Your dual variable for constraint d857
  cpg_float    *d858;      // Your dual variable for constraint d858
  cpg_float    d859;       // Your dual variable for constraint d859
  cpg_float    d860;       // Your dual variable for constraint d860
  cpg_float    d861;       // Your dual variable for constraint d861
  cpg_float    d862;       // Your dual variable for constraint d862
  cpg_float    d863;       // Your dual variable for constraint d863
  cpg_float    d864;       // Your dual variable for constraint d864
  cpg_float    d865;       // Your dual variable for constraint d865
  cpg_float    d866;       // Your dual variable for constraint d866
  cpg_float    d867;       // Your dual variable for constraint d867
  cpg_float    *d868;      // Your dual variable for constraint d868
  cpg_float    *d869;      // Your dual variable for constraint d869
  cpg_float    d870;       // Your dual variable for constraint d870
  cpg_float    d871;       // Your dual variable for constraint d871
  cpg_float    d872;       // Your dual variable for constraint d872
  cpg_float    d873;       // Your dual variable for constraint d873
  cpg_float    d874;       // Your dual variable for constraint d874
  cpg_float    d875;       // Your dual variable for constraint d875
  cpg_float    d876;       // Your dual variable for constraint d876
  cpg_float    d877;       // Your dual variable for constraint d877
  cpg_float    d878;       // Your dual variable for constraint d878
  cpg_float    *d879;      // Your dual variable for constraint d879
  cpg_float    *d880;      // Your dual variable for constraint d880
  cpg_float    d881;       // Your dual variable for constraint d881
  cpg_float    d882;       // Your dual variable for constraint d882
  cpg_float    d883;       // Your dual variable for constraint d883
  cpg_float    d884;       // Your dual variable for constraint d884
  cpg_float    d885;       // Your dual variable for constraint d885
  cpg_float    d886;       // Your dual variable for constraint d886
  cpg_float    d887;       // Your dual variable for constraint d887
  cpg_float    d888;       // Your dual variable for constraint d888
  cpg_float    d889;       // Your dual variable for constraint d889
  cpg_float    *d890;      // Your dual variable for constraint d890
  cpg_float    *d891;      // Your dual variable for constraint d891
  cpg_float    d892;       // Your dual variable for constraint d892
  cpg_float    d893;       // Your dual variable for constraint d893
  cpg_float    d894;       // Your dual variable for constraint d894
  cpg_float    d895;       // Your dual variable for constraint d895
  cpg_float    d896;       // Your dual variable for constraint d896
  cpg_float    d897;       // Your dual variable for constraint d897
  cpg_float    d898;       // Your dual variable for constraint d898
  cpg_float    d899;       // Your dual variable for constraint d899
  cpg_float    d900;       // Your dual variable for constraint d900
  cpg_float    *d901;      // Your dual variable for constraint d901
  cpg_float    *d902;      // Your dual variable for constraint d902
  cpg_float    d903;       // Your dual variable for constraint d903
  cpg_float    d904;       // Your dual variable for constraint d904
  cpg_float    d905;       // Your dual variable for constraint d905
  cpg_float    d906;       // Your dual variable for constraint d906
  cpg_float    d907;       // Your dual variable for constraint d907
  cpg_float    d908;       // Your dual variable for constraint d908
  cpg_float    d909;       // Your dual variable for constraint d909
  cpg_float    d910;       // Your dual variable for constraint d910
  cpg_float    d911;       // Your dual variable for constraint d911
  cpg_float    *d912;      // Your dual variable for constraint d912
  cpg_float    *d913;      // Your dual variable for constraint d913
  cpg_float    d914;       // Your dual variable for constraint d914
  cpg_float    d915;       // Your dual variable for constraint d915
  cpg_float    d916;       // Your dual variable for constraint d916
  cpg_float    d917;       // Your dual variable for constraint d917
  cpg_float    d918;       // Your dual variable for constraint d918
  cpg_float    d919;       // Your dual variable for constraint d919
  cpg_float    d920;       // Your dual variable for constraint d920
  cpg_float    d921;       // Your dual variable for constraint d921
  cpg_float    d922;       // Your dual variable for constraint d922
  cpg_float    *d923;      // Your dual variable for constraint d923
  cpg_float    *d924;      // Your dual variable for constraint d924
  cpg_float    d925;       // Your dual variable for constraint d925
  cpg_float    d926;       // Your dual variable for constraint d926
  cpg_float    d927;       // Your dual variable for constraint d927
  cpg_float    d928;       // Your dual variable for constraint d928
  cpg_float    d929;       // Your dual variable for constraint d929
  cpg_float    d930;       // Your dual variable for constraint d930
  cpg_float    d931;       // Your dual variable for constraint d931
  cpg_float    d932;       // Your dual variable for constraint d932
  cpg_float    d933;       // Your dual variable for constraint d933
  cpg_float    *d934;      // Your dual variable for constraint d934
  cpg_float    *d935;      // Your dual variable for constraint d935
  cpg_float    d936;       // Your dual variable for constraint d936
  cpg_float    d937;       // Your dual variable for constraint d937
  cpg_float    d938;       // Your dual variable for constraint d938
  cpg_float    d939;       // Your dual variable for constraint d939
  cpg_float    d940;       // Your dual variable for constraint d940
  cpg_float    d941;       // Your dual variable for constraint d941
  cpg_float    d942;       // Your dual variable for constraint d942
  cpg_float    d943;       // Your dual variable for constraint d943
  cpg_float    d944;       // Your dual variable for constraint d944
  cpg_float    *d945;      // Your dual variable for constraint d945
  cpg_float    *d946;      // Your dual variable for constraint d946
  cpg_float    d947;       // Your dual variable for constraint d947
  cpg_float    d948;       // Your dual variable for constraint d948
  cpg_float    d949;       // Your dual variable for constraint d949
  cpg_float    d950;       // Your dual variable for constraint d950
  cpg_float    d951;       // Your dual variable for constraint d951
  cpg_float    d952;       // Your dual variable for constraint d952
  cpg_float    d953;       // Your dual variable for constraint d953
  cpg_float    d954;       // Your dual variable for constraint d954
  cpg_float    d955;       // Your dual variable for constraint d955
  cpg_float    *d956;      // Your dual variable for constraint d956
  cpg_float    *d957;      // Your dual variable for constraint d957
  cpg_float    d958;       // Your dual variable for constraint d958
  cpg_float    d959;       // Your dual variable for constraint d959
  cpg_float    d960;       // Your dual variable for constraint d960
  cpg_float    d961;       // Your dual variable for constraint d961
  cpg_float    d962;       // Your dual variable for constraint d962
  cpg_float    d963;       // Your dual variable for constraint d963
  cpg_float    d964;       // Your dual variable for constraint d964
  cpg_float    d965;       // Your dual variable for constraint d965
  cpg_float    d966;       // Your dual variable for constraint d966
  cpg_float    *d967;      // Your dual variable for constraint d967
  cpg_float    *d968;      // Your dual variable for constraint d968
  cpg_float    d969;       // Your dual variable for constraint d969
  cpg_float    d970;       // Your dual variable for constraint d970
  cpg_float    d971;       // Your dual variable for constraint d971
  cpg_float    d972;       // Your dual variable for constraint d972
  cpg_float    d973;       // Your dual variable for constraint d973
  cpg_float    d974;       // Your dual variable for constraint d974
  cpg_float    d975;       // Your dual variable for constraint d975
  cpg_float    d976;       // Your dual variable for constraint d976
  cpg_float    d977;       // Your dual variable for constraint d977
  cpg_float    *d978;      // Your dual variable for constraint d978
  cpg_float    *d979;      // Your dual variable for constraint d979
  cpg_float    d980;       // Your dual variable for constraint d980
  cpg_float    d981;       // Your dual variable for constraint d981
  cpg_float    d982;       // Your dual variable for constraint d982
  cpg_float    d983;       // Your dual variable for constraint d983
  cpg_float    d984;       // Your dual variable for constraint d984
  cpg_float    d985;       // Your dual variable for constraint d985
  cpg_float    d986;       // Your dual variable for constraint d986
  cpg_float    d987;       // Your dual variable for constraint d987
  cpg_float    d988;       // Your dual variable for constraint d988
  cpg_float    *d989;      // Your dual variable for constraint d989
  cpg_float    *d990;      // Your dual variable for constraint d990
  cpg_float    d991;       // Your dual variable for constraint d991
  cpg_float    d992;       // Your dual variable for constraint d992
  cpg_float    d993;       // Your dual variable for constraint d993
  cpg_float    d994;       // Your dual variable for constraint d994
  cpg_float    d995;       // Your dual variable for constraint d995
  cpg_float    d996;       // Your dual variable for constraint d996
  cpg_float    d997;       // Your dual variable for constraint d997
  cpg_float    d998;       // Your dual variable for constraint d998
  cpg_float    d999;       // Your dual variable for constraint d999
  cpg_float    *d1000;     // Your dual variable for constraint d1000
  cpg_float    *d1001;     // Your dual variable for constraint d1001
  cpg_float    d1002;      // Your dual variable for constraint d1002
  cpg_float    d1003;      // Your dual variable for constraint d1003
  cpg_float    d1004;      // Your dual variable for constraint d1004
  cpg_float    d1005;      // Your dual variable for constraint d1005
  cpg_float    d1006;      // Your dual variable for constraint d1006
  cpg_float    d1007;      // Your dual variable for constraint d1007
  cpg_float    d1008;      // Your dual variable for constraint d1008
  cpg_float    d1009;      // Your dual variable for constraint d1009
  cpg_float    d1010;      // Your dual variable for constraint d1010
  cpg_float    *d1011;     // Your dual variable for constraint d1011
  cpg_float    *d1012;     // Your dual variable for constraint d1012
  cpg_float    d1013;      // Your dual variable for constraint d1013
  cpg_float    d1014;      // Your dual variable for constraint d1014
  cpg_float    d1015;      // Your dual variable for constraint d1015
  cpg_float    d1016;      // Your dual variable for constraint d1016
  cpg_float    d1017;      // Your dual variable for constraint d1017
  cpg_float    d1018;      // Your dual variable for constraint d1018
  cpg_float    d1019;      // Your dual variable for constraint d1019
  cpg_float    d1020;      // Your dual variable for constraint d1020
  cpg_float    d1021;      // Your dual variable for constraint d1021
  cpg_float    *d1022;     // Your dual variable for constraint d1022
  cpg_float    *d1023;     // Your dual variable for constraint d1023
  cpg_float    d1024;      // Your dual variable for constraint d1024
  cpg_float    d1025;      // Your dual variable for constraint d1025
  cpg_float    d1026;      // Your dual variable for constraint d1026
  cpg_float    d1027;      // Your dual variable for constraint d1027
  cpg_float    d1028;      // Your dual variable for constraint d1028
  cpg_float    d1029;      // Your dual variable for constraint d1029
  cpg_float    d1030;      // Your dual variable for constraint d1030
  cpg_float    d1031;      // Your dual variable for constraint d1031
  cpg_float    d1032;      // Your dual variable for constraint d1032
  cpg_float    *d1033;     // Your dual variable for constraint d1033
  cpg_float    *d1034;     // Your dual variable for constraint d1034
  cpg_float    d1035;      // Your dual variable for constraint d1035
  cpg_float    d1036;      // Your dual variable for constraint d1036
  cpg_float    d1037;      // Your dual variable for constraint d1037
  cpg_float    d1038;      // Your dual variable for constraint d1038
  cpg_float    d1039;      // Your dual variable for constraint d1039
  cpg_float    d1040;      // Your dual variable for constraint d1040
  cpg_float    d1041;      // Your dual variable for constraint d1041
  cpg_float    d1042;      // Your dual variable for constraint d1042
  cpg_float    d1043;      // Your dual variable for constraint d1043
  cpg_float    *d1044;     // Your dual variable for constraint d1044
  cpg_float    *d1045;     // Your dual variable for constraint d1045
  cpg_float    d1046;      // Your dual variable for constraint d1046
  cpg_float    d1047;      // Your dual variable for constraint d1047
  cpg_float    d1048;      // Your dual variable for constraint d1048
  cpg_float    d1049;      // Your dual variable for constraint d1049
  cpg_float    d1050;      // Your dual variable for constraint d1050
  cpg_float    d1051;      // Your dual variable for constraint d1051
  cpg_float    d1052;      // Your dual variable for constraint d1052
  cpg_float    d1053;      // Your dual variable for constraint d1053
  cpg_float    d1054;      // Your dual variable for constraint d1054
  cpg_float    *d1055;     // Your dual variable for constraint d1055
  cpg_float    *d1056;     // Your dual variable for constraint d1056
  cpg_float    d1057;      // Your dual variable for constraint d1057
  cpg_float    d1058;      // Your dual variable for constraint d1058
  cpg_float    d1059;      // Your dual variable for constraint d1059
  cpg_float    d1060;      // Your dual variable for constraint d1060
  cpg_float    d1061;      // Your dual variable for constraint d1061
  cpg_float    d1062;      // Your dual variable for constraint d1062
  cpg_float    d1063;      // Your dual variable for constraint d1063
  cpg_float    d1064;      // Your dual variable for constraint d1064
  cpg_float    d1065;      // Your dual variable for constraint d1065
  cpg_float    *d1066;     // Your dual variable for constraint d1066
  cpg_float    *d1067;     // Your dual variable for constraint d1067
  cpg_float    d1068;      // Your dual variable for constraint d1068
  cpg_float    d1069;      // Your dual variable for constraint d1069
  cpg_float    d1070;      // Your dual variable for constraint d1070
  cpg_float    d1071;      // Your dual variable for constraint d1071
  cpg_float    d1072;      // Your dual variable for constraint d1072
  cpg_float    d1073;      // Your dual variable for constraint d1073
  cpg_float    d1074;      // Your dual variable for constraint d1074
  cpg_float    d1075;      // Your dual variable for constraint d1075
  cpg_float    d1076;      // Your dual variable for constraint d1076
  cpg_float    *d1077;     // Your dual variable for constraint d1077
  cpg_float    *d1078;     // Your dual variable for constraint d1078
  cpg_float    d1079;      // Your dual variable for constraint d1079
  cpg_float    d1080;      // Your dual variable for constraint d1080
  cpg_float    d1081;      // Your dual variable for constraint d1081
  cpg_float    d1082;      // Your dual variable for constraint d1082
  cpg_float    d1083;      // Your dual variable for constraint d1083
  cpg_float    d1084;      // Your dual variable for constraint d1084
  cpg_float    d1085;      // Your dual variable for constraint d1085
  cpg_float    d1086;      // Your dual variable for constraint d1086
  cpg_float    d1087;      // Your dual variable for constraint d1087
  cpg_float    *d1088;     // Your dual variable for constraint d1088
  cpg_float    *d1089;     // Your dual variable for constraint d1089
  cpg_float    d1090;      // Your dual variable for constraint d1090
  cpg_float    d1091;      // Your dual variable for constraint d1091
  cpg_float    d1092;      // Your dual variable for constraint d1092
  cpg_float    d1093;      // Your dual variable for constraint d1093
  cpg_float    d1094;      // Your dual variable for constraint d1094
  cpg_float    d1095;      // Your dual variable for constraint d1095
  cpg_float    d1096;      // Your dual variable for constraint d1096
  cpg_float    d1097;      // Your dual variable for constraint d1097
  cpg_float    d1098;      // Your dual variable for constraint d1098
  cpg_float    *d1099;     // Your dual variable for constraint d1099
  cpg_float    *d1100;     // Your dual variable for constraint d1100
  cpg_float    d1101;      // Your dual variable for constraint d1101
  cpg_float    d1102;      // Your dual variable for constraint d1102
  cpg_float    d1103;      // Your dual variable for constraint d1103
} CPG_Dual_t;

// Solver information
typedef struct {
  cpg_float    obj_val;    // Objective function value
  cpg_int      iter;       // Number of iterations
  cpg_int      status;     // Solver status
  cpg_float    pri_res;    // Primal residual
  cpg_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;        // Primal solution
  CPG_Dual_t *dual;        // Dual solution
  CPG_Info_t *info;        // Solver info
} CPG_Result_t;

// Parameter deltas
typedef struct {
  cpg_float    *initial_position;   // Delta of your parameter initial_position
  cpg_float    *initial_velocity;   // Delta of your parameter initial_velocity
  cpg_float    *log_mass;   // Delta of your parameter log_mass
  cpg_float    *max_vel;   // Delta of your parameter max_vel
  cpg_float    *sin_glide_slope;   // Delta of your parameter sin_glide_slope
  cpg_float    *z0;        // Delta of your parameter z0
  cpg_float    *min_exp_z0;   // Delta of your parameter min_exp_z0
  cpg_float    *max_exp_z0;   // Delta of your parameter max_exp_z0
  cpg_float    *dt;        // Delta of your parameter dt
  cpg_float    *dt_squared;   // Delta of your parameter dt_squared
  cpg_float    *gravity_dt_squared;   // Delta of your parameter gravity_dt_squared
  cpg_float    *gravity_dt;   // Delta of your parameter gravity_dt
  cpg_float    *fuel_consumption_dt;   // Delta of your parameter fuel_consumption_dt
  cpg_float    *target_velocity;   // Delta of your parameter target_velocity
  cpg_float    *log_dry_mass;   // Delta of your parameter log_dry_mass
} CPG_Delta_t;

// Solver settings
typedef struct {
  cpg_int    max_iters;
  cpg_int    bisect_iters;
  cpg_int    ruiz_iters;
  cpg_int    iter_ref_iters;
  cpg_float  kkt_static_reg;
  cpg_float  kkt_dynamic_reg;
  cpg_float  abstol;
  cpg_float  reltol;
  cpg_float  abstol_inacc;
  cpg_float  reltol_inacc;
  cpg_int    verbose;
} Canon_Settings_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern cpg_float cpg_params_vec[323];

// Sparse mappings from user-defined to canonical parameters
extern cpg_csc canon_A_map;
extern cpg_csc canon_b_map;
extern cpg_csc canon_G_map;
extern cpg_csc canon_h_map;

// Canonical parameters
extern cpg_float canon_c[1500];
extern cpg_float canon_c_conditioning[1500];
extern cpg_csc canon_A;
extern cpg_csc canon_A_conditioning;
extern cpg_float canon_b[708];
extern cpg_float canon_b_conditioning[708];
extern cpg_csc canon_G;
extern cpg_csc canon_G_conditioning;
extern cpg_float canon_h[2300];
extern cpg_float canon_h_conditioning[2300];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;
extern Canon_Params_t Canon_Params_conditioning;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// User-defined variables
extern cpg_float cpg_z[100];
extern cpg_float cpg_x[600];
extern cpg_float cpg_u[300];
extern cpg_float cpg_s[100];

// Dual variables associated with user-defined constraints
extern cpg_float cpg_d0[3];
extern cpg_float cpg_d1[3];
extern cpg_float cpg_d10[3];
extern cpg_float cpg_d11[3];
extern cpg_float cpg_d21[3];
extern cpg_float cpg_d22[3];
extern cpg_float cpg_d32[3];
extern cpg_float cpg_d33[3];
extern cpg_float cpg_d43[3];
extern cpg_float cpg_d44[3];
extern cpg_float cpg_d54[3];
extern cpg_float cpg_d55[3];
extern cpg_float cpg_d65[3];
extern cpg_float cpg_d66[3];
extern cpg_float cpg_d76[3];
extern cpg_float cpg_d77[3];
extern cpg_float cpg_d87[3];
extern cpg_float cpg_d88[3];
extern cpg_float cpg_d98[3];
extern cpg_float cpg_d99[3];
extern cpg_float cpg_d109[3];
extern cpg_float cpg_d110[3];
extern cpg_float cpg_d120[3];
extern cpg_float cpg_d121[3];
extern cpg_float cpg_d131[3];
extern cpg_float cpg_d132[3];
extern cpg_float cpg_d142[3];
extern cpg_float cpg_d143[3];
extern cpg_float cpg_d153[3];
extern cpg_float cpg_d154[3];
extern cpg_float cpg_d164[3];
extern cpg_float cpg_d165[3];
extern cpg_float cpg_d175[3];
extern cpg_float cpg_d176[3];
extern cpg_float cpg_d186[3];
extern cpg_float cpg_d187[3];
extern cpg_float cpg_d197[3];
extern cpg_float cpg_d198[3];
extern cpg_float cpg_d208[3];
extern cpg_float cpg_d209[3];
extern cpg_float cpg_d219[3];
extern cpg_float cpg_d220[3];
extern cpg_float cpg_d230[3];
extern cpg_float cpg_d231[3];
extern cpg_float cpg_d241[3];
extern cpg_float cpg_d242[3];
extern cpg_float cpg_d252[3];
extern cpg_float cpg_d253[3];
extern cpg_float cpg_d263[3];
extern cpg_float cpg_d264[3];
extern cpg_float cpg_d274[3];
extern cpg_float cpg_d275[3];
extern cpg_float cpg_d285[3];
extern cpg_float cpg_d286[3];
extern cpg_float cpg_d296[3];
extern cpg_float cpg_d297[3];
extern cpg_float cpg_d307[3];
extern cpg_float cpg_d308[3];
extern cpg_float cpg_d318[3];
extern cpg_float cpg_d319[3];
extern cpg_float cpg_d329[3];
extern cpg_float cpg_d330[3];
extern cpg_float cpg_d340[3];
extern cpg_float cpg_d341[3];
extern cpg_float cpg_d351[3];
extern cpg_float cpg_d352[3];
extern cpg_float cpg_d362[3];
extern cpg_float cpg_d363[3];
extern cpg_float cpg_d373[3];
extern cpg_float cpg_d374[3];
extern cpg_float cpg_d384[3];
extern cpg_float cpg_d385[3];
extern cpg_float cpg_d395[3];
extern cpg_float cpg_d396[3];
extern cpg_float cpg_d406[3];
extern cpg_float cpg_d407[3];
extern cpg_float cpg_d417[3];
extern cpg_float cpg_d418[3];
extern cpg_float cpg_d428[3];
extern cpg_float cpg_d429[3];
extern cpg_float cpg_d439[3];
extern cpg_float cpg_d440[3];
extern cpg_float cpg_d450[3];
extern cpg_float cpg_d451[3];
extern cpg_float cpg_d461[3];
extern cpg_float cpg_d462[3];
extern cpg_float cpg_d472[3];
extern cpg_float cpg_d473[3];
extern cpg_float cpg_d483[3];
extern cpg_float cpg_d484[3];
extern cpg_float cpg_d494[3];
extern cpg_float cpg_d495[3];
extern cpg_float cpg_d505[3];
extern cpg_float cpg_d506[3];
extern cpg_float cpg_d516[3];
extern cpg_float cpg_d517[3];
extern cpg_float cpg_d527[3];
extern cpg_float cpg_d528[3];
extern cpg_float cpg_d538[3];
extern cpg_float cpg_d539[3];
extern cpg_float cpg_d549[3];
extern cpg_float cpg_d550[3];
extern cpg_float cpg_d560[3];
extern cpg_float cpg_d561[3];
extern cpg_float cpg_d571[3];
extern cpg_float cpg_d572[3];
extern cpg_float cpg_d582[3];
extern cpg_float cpg_d583[3];
extern cpg_float cpg_d593[3];
extern cpg_float cpg_d594[3];
extern cpg_float cpg_d604[3];
extern cpg_float cpg_d605[3];
extern cpg_float cpg_d615[3];
extern cpg_float cpg_d616[3];
extern cpg_float cpg_d626[3];
extern cpg_float cpg_d627[3];
extern cpg_float cpg_d637[3];
extern cpg_float cpg_d638[3];
extern cpg_float cpg_d648[3];
extern cpg_float cpg_d649[3];
extern cpg_float cpg_d659[3];
extern cpg_float cpg_d660[3];
extern cpg_float cpg_d670[3];
extern cpg_float cpg_d671[3];
extern cpg_float cpg_d681[3];
extern cpg_float cpg_d682[3];
extern cpg_float cpg_d692[3];
extern cpg_float cpg_d693[3];
extern cpg_float cpg_d703[3];
extern cpg_float cpg_d704[3];
extern cpg_float cpg_d714[3];
extern cpg_float cpg_d715[3];
extern cpg_float cpg_d725[3];
extern cpg_float cpg_d726[3];
extern cpg_float cpg_d736[3];
extern cpg_float cpg_d737[3];
extern cpg_float cpg_d747[3];
extern cpg_float cpg_d748[3];
extern cpg_float cpg_d758[3];
extern cpg_float cpg_d759[3];
extern cpg_float cpg_d769[3];
extern cpg_float cpg_d770[3];
extern cpg_float cpg_d780[3];
extern cpg_float cpg_d781[3];
extern cpg_float cpg_d791[3];
extern cpg_float cpg_d792[3];
extern cpg_float cpg_d802[3];
extern cpg_float cpg_d803[3];
extern cpg_float cpg_d813[3];
extern cpg_float cpg_d814[3];
extern cpg_float cpg_d824[3];
extern cpg_float cpg_d825[3];
extern cpg_float cpg_d835[3];
extern cpg_float cpg_d836[3];
extern cpg_float cpg_d846[3];
extern cpg_float cpg_d847[3];
extern cpg_float cpg_d857[3];
extern cpg_float cpg_d858[3];
extern cpg_float cpg_d868[3];
extern cpg_float cpg_d869[3];
extern cpg_float cpg_d879[3];
extern cpg_float cpg_d880[3];
extern cpg_float cpg_d890[3];
extern cpg_float cpg_d891[3];
extern cpg_float cpg_d901[3];
extern cpg_float cpg_d902[3];
extern cpg_float cpg_d912[3];
extern cpg_float cpg_d913[3];
extern cpg_float cpg_d923[3];
extern cpg_float cpg_d924[3];
extern cpg_float cpg_d934[3];
extern cpg_float cpg_d935[3];
extern cpg_float cpg_d945[3];
extern cpg_float cpg_d946[3];
extern cpg_float cpg_d956[3];
extern cpg_float cpg_d957[3];
extern cpg_float cpg_d967[3];
extern cpg_float cpg_d968[3];
extern cpg_float cpg_d978[3];
extern cpg_float cpg_d979[3];
extern cpg_float cpg_d989[3];
extern cpg_float cpg_d990[3];
extern cpg_float cpg_d1000[3];
extern cpg_float cpg_d1001[3];
extern cpg_float cpg_d1011[3];
extern cpg_float cpg_d1012[3];
extern cpg_float cpg_d1022[3];
extern cpg_float cpg_d1023[3];
extern cpg_float cpg_d1033[3];
extern cpg_float cpg_d1034[3];
extern cpg_float cpg_d1044[3];
extern cpg_float cpg_d1045[3];
extern cpg_float cpg_d1055[3];
extern cpg_float cpg_d1056[3];
extern cpg_float cpg_d1066[3];
extern cpg_float cpg_d1067[3];
extern cpg_float cpg_d1077[3];
extern cpg_float cpg_d1078[3];
extern cpg_float cpg_d1088[3];
extern cpg_float cpg_d1089[3];
extern cpg_float cpg_d1099[3];
extern cpg_float cpg_d1100[3];

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing dual solution
extern CPG_Dual_t CPG_Dual;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;

// Struct containing solver settings
extern Canon_Settings_t Canon_Settings;

// QOCO array of SOC dimensions
extern cpg_int qoco_q[400];

// QOCO workspace
extern QOCOSolver* qoco_solver;

// QOCO exit flag
extern cpg_int qoco_flag;
