# GUIDIANCE SETTINGS:
SKIP_BOOSTERBACK = False
SKIP_AERODYNAMIC_GUIDANCE = False
SKIP_ENTRYBURN = True

# GLOBAL SETTINGS:
MAX_TILT = 30
THROTTLE_LIMIT = [0.1, 1]

# GFOLD PARAMS:
GFOLD_START_VELOCITY = 340

# OTHER SETTINGS:
LAND_CONFIRM = False
LANDING_GEAR = False
FINAL_ALTITUDE = 50 # set to 0 to disable