# GUIDIANCE SETTINGS:
SKIP_BOOSTERBACK = False
SKIP_AERODYNAMIC_GUIDANCE = False
SKIP_ENTRYBURN = True

# GLOBAL SETTINGS:
MAX_TILT = 30
THROTTLE_LIMIT = [0.1, 1]
TARGET_ROLL = 0

# GFOLD PARAMS:
GFOLD_START_VELOCITY = 140

# OTHER SETTINGS:
LAND_CONFIRM = True
LANDING_GEAR = True
FINAL_ALTITUDE = 0 # set to 0 to disable